// The guided course: units of about a week each, following the study program
// (Phase 0 re-entry, Phase 1 N5 core, Phase 2 N4 bridge).
// Each unit has a goal, 3-5 grammar points with examples, and practice tagged from the existing modes:
//   trains: indexes into TRAINS (Particle Train), story: { chapter, from, to } beat range (0-based, inclusive),
//   shop: counter ids from COUNTERS (Shopkeeper), phrases: PHRASES ids (Rhythm).
// vocab: the unit's key words from the N5 deck (N5_WORDS, by written form), shown with their pitch accent.
// Examples are original lines, some voiced by the story cast. voice: 0 narrator, 1 Ren, 2 Master, 3 Kaito
// (voice 3 is also the polite shop customer, so the shop orders below reuse its existing clips).
// Readings are hiragana with the same spacing as the line; katakana names are written in hiragana, as in the story.

const X = (jp, reading, en, voice = 0) => ({ jp, reading, en, voice });
const GP = (id, title, pattern, explain, examples) => ({ id, title, pattern, explain, examples });

/** A unit completes when, over at least MIN_ANSWERS first-try answers in its practice, the recent ones are ≥ TARGET. */
export const UNIT_TARGET = 0.85;
export const UNIT_MIN_ANSWERS = 20;
export const UNIT_WINDOW = 30;

export const PHASES = [
  { id: 'p0', n: 0, title: 'Re-entry', when: 'Weeks 1–2',
    focus: 'Refresh kana and the starter phrases, try every mode once, find your pace.' },
  { id: 'p1', n: 1, title: 'N5 core', when: 'Weeks 3–10',
    focus: 'です and ます forms, the core particles, adjectives, counters and your first requests.' },
  { id: 'p2', n: 2, title: 'N4 bridge', when: 'Months 3–6',
    focus: 'Te-form chains, plain and casual speech (the way anime characters talk), reasons and plans.' },
];

export const UNITS = [
  // ---------------- Phase 0: re-entry ----------------
  { id: 'p0-1', phase: 'p0', title: 'Say hello and introduce yourself',
    goal: 'Greet people and say who you are.',
    points: [
      GP('greetings', 'Greetings are set phrases', 'おはよう / こんにちは / はじめまして',
        'Greetings are learned as whole chunks. Adding ございます to おはよう makes it polite, the way you greet a teacher or a master.',
        [X('おはよう ございます、師匠！', 'おはよう ございます、ししょう！', 'Good morning, Master!', 1),
          X('はじめまして。レンです。', 'はじめまして。れんです。', "Nice to meet you. I'm Ren.", 1)]),
      GP('desu', 'です: "is, am, are"', 'N です',
        'です ends a polite sentence and works like "is", "am" or "are". It never changes for I, you or he. The subject is often left out when it is obvious.',
        [X('わたしは 学生です。', 'わたしは がくせいです。', "I'm a student.")]),
      GP('wa', 'は marks the topic', 'X は Y です',
        'は (written は, said "wa") marks what you are talking about: "As for X, it is Y." It is the most common way to start a sentence.',
        [X('師匠は 先生です。', 'ししょうは せんせいです。', 'The Master is a teacher.')]),
      GP('ka', 'か makes a question', '… ですか。',
        'Put か at the end of a polite sentence to make it a yes/no question. Answer with はい (yes) or いいえ (no).',
        [X('先生ですか。', 'せんせいですか。', 'Are you a teacher?', 1),
          X('いいえ、学生です。', 'いいえ、がくせいです。', "No, I'm a student.")]),
    ],
    vocab: ['私', '学生', '先生', '名前', 'はい', 'いいえ'],
    practice: { trains: [1, 5], story: { chapter: 'ch1', from: 0, to: 4 }, phrases: ['ohayou', 'konnichiwa', 'konbanwa', 'hajimemashite', 'arigatou', 'sayounara'] } },

  { id: 'p0-2', phase: 'p0', title: 'Ask what things are, and whose',
    goal: 'Point at things, ask what they are and say whose they are.',
    points: [
      GP('kosoado', 'これ・それ・あれ: this, that, that over there', 'これ / それ / あれ は N です',
        'これ is near me, それ is near you, あれ is far from both of us. They stand on their own like nouns.',
        [X('これは 本です。', 'これは ほんです。', 'This is a book.')]),
      GP('nan', 'なん / なに: "what"', 'N は なんですか。',
        'なに means "what". Right before です it usually becomes なん: それは なんですか.',
        [X('それは なんですか。', 'それは なんですか。', 'What is that?', 1)]),
      GP('no', 'の links nouns: "\'s"', 'A の B',
        'A の B means "A\'s B" or "the B of A": the owner or the group comes first. あの / この / その also point: "that ___", "this ___".',
        [X('師匠の 道場です。', 'ししょうの どうじょうです。', "It's the Master's dojo.", 1),
          X('あれは だれの かばんですか。', 'あれは だれの かばんですか。', 'Whose bag is that?')]),
      GP('da', 'だ: casual です', 'N だ',
        'だ is the plain, casual form of です. Friends and tough anime characters use it all the time; keep です for strangers and teachers.',
        [X('ここは おれの 町だ。', 'ここは おれの まちだ。', 'This is my town.', 3)]),
    ],
    vocab: ['これ', 'それ', 'あれ', '本', '鞄', '何', 'ここ'],
    practice: { trains: [5, 1], story: { chapter: 'ch1', from: 3, to: 7 }, phrases: ['sensei', 'gakusei', 'nihon', 'toukyou', 'sumimasen', 'wakarimashita'] } },

  // ---------------- Phase 1: N5 core ----------------
  { id: 'p1-1', phase: 'p1', title: 'Talk about what you like',
    goal: 'Say what you like and don\'t like, and ask others.',
    points: [
      GP('suki', 'N が すきです: "I like N"', 'N が すきです',
        'すき works like an adjective ("likable"), so the thing you like takes が, not を.',
        [X('ラーメンが すきです。', 'らーめんが すきです。', 'I like ramen.', 1)]),
      GP('mo', 'も: "too, also"', 'N も …',
        'も means "also". It replaces は or が instead of adding to them: おれも, never おれはも.',
        [X('おれも ラーメンが すきだ。', 'おれも らーめんが すきだ。', 'I like ramen too.', 3)]),
      GP('to-and', 'と: "and" between nouns', 'A と B',
        'と joins two nouns: "A and B". It is only for nouns, never for joining sentences.',
        [X('すしと てんぷらが すきです。', 'すしと てんぷらが すきです。', 'I like sushi and tempura.')]),
      GP('nani-ga', 'Asking and saying "not really"', 'なにが すきですか。 / N は すきじゃないです。',
        'Ask with なにが すきですか. To say you don\'t like something, use じゃないです, the negative of です. は often replaces が here to contrast it with other things.',
        [X('なにが すきですか。', 'なにが すきですか。', 'What do you like?', 2),
          X('コーヒーは すきじゃないです。', 'こーひーは すきじゃないです。', "I don't like coffee.", 1)]),
    ],
    vocab: ['好き', '嫌い', 'コーヒー', '猫', '犬', '水'],
    practice: { trains: [6, 10, 0], story: { chapter: 'ch1', from: 3, to: 5 }, phrases: ['neko', 'inu', 'mizu', 'daijoubu'] } },

  { id: 'p1-2', phase: 'p1', title: 'Say what you do every day',
    goal: 'Talk about your daily routine with polite verbs.',
    points: [
      GP('masu', 'Verbs in ます form', 'V-ます',
        'The ます form is the polite way to say what you do or will do. Japanese has no separate future: たべます is "I eat" or "I will eat".',
        [X('毎日 はしります。', 'まいにち はしります。', 'I run every day.', 1)]),
      GP('wo', 'を marks the object', 'N を V-ます',
        'を (said "o") marks the thing the action is done to: eat WHAT, drink WHAT, watch WHAT.',
        [X('ラーメンを たべます。', 'らーめんを たべます。', 'I eat ramen.'),
          X('水を のみます。', 'みずを のみます。', 'I drink water.')]),
      GP('masen', 'ません: "don\'t, won\'t"', 'V-ません',
        'Swap ます for ません to make it negative. A は in place of を adds "…but not that".',
        [X('コーヒーは のみません。', 'こーひーは のみません。', "I don't drink coffee.", 1)]),
      GP('time-words', 'Time words need no particle', '毎日 / きょう / あした + V-ます',
        'Relative time words like 毎日 (every day), きょう (today) and あした (tomorrow) sit at the start with no particle.',
        [X('あした また きます。', 'あした また きます。', "I'll come again tomorrow.", 1)]),
    ],
    vocab: ['食べる', '飲む', '走る', '毎日', '今日', '明日', '来る'],
    practice: { trains: [0, 7, 2], story: { chapter: 'ch3', from: 0, to: 4 }, phrases: ['itadakimasu', 'mizu', 'wakarimashita'] } },

  { id: 'p1-3', phase: 'p1', title: 'Say where you\'re going and how',
    goal: 'Talk about going places: where to, where, how and with whom.',
    points: [
      GP('ni-he', 'に / へ: "to" a place', 'Place に (へ) いきます',
        'に or へ (said "e") marks where you are headed. With いきます (go), きます (come) and かえります (go home) either one works.',
        [X('道場に いきます。', 'どうじょうに いきます。', "I'm going to the dojo.", 1)]),
      GP('de-place', 'で: where an action happens', 'Place で V-ます',
        'で marks the place where you DO something. Compare: 道場に いきます (go to the dojo), 道場で はしります (run at the dojo).',
        [X('へやで ゲームを します。', 'へやで げーむを します。', 'I play video games in my room.', 1)]),
      GP('de-means', 'で: "by, with" a means', 'N で V-ます',
        'で also marks the tool or transport you use: by bus, by train, with a pen.',
        [X('バスで がっこうに いきます。', 'ばすで がっこうに いきます。', 'I go to school by bus.')]),
      GP('to-with', 'と: "with" someone', 'Person と V-ます',
        'After a person, と means "together with".',
        [X('ともだちと えきに いきます。', 'ともだちと えきに いきます。', "I'm going to the station with a friend.")]),
    ],
    vocab: ['行く', '帰る', '電車', 'バス', '学校', '駅', '友達', '部屋'],
    practice: { trains: [2, 3, 4, 11], story: { chapter: 'ch2', from: 0, to: 5 }, phrases: ['toukyou', 'nihon'] } },

  { id: 'p1-4', phase: 'p1', title: 'Order food',
    goal: 'Order food and drinks at a shop or restaurant.',
    points: [
      GP('kudasai', 'N を ください: "N, please"', 'N を ください。',
        'ください asks someone to give you something. It is the standard, polite way to order.',
        [X('ラーメンを ください。', 'らーめんを ください。', 'Ramen, please.', 1)]),
      GP('count-order', 'How many: noun, を, number', 'N を ふたつ ください。',
        'The number comes after the thing and its particle, right before the verb. ひとつ, ふたつ, みっつ count small things in general.',
        [X('りんごを ふたつ ください。', 'りんごを ふたつ ください。', 'Two apples, please.', 3)]),
      GP('onegai', 'おねがいします: a softer "please"', 'N を おねがいします。',
        'おねがいします also works for ordering, and for any favour. It sounds a little softer than ください.',
        [X('おちゃを おねがいします。', 'おちゃを おねがいします。', 'Green tea, please.', 1)]),
      GP('ikura', 'いくら: "how much?"', 'N は いくらですか。',
        'いくら asks about a price. A shop greets you with いらっしゃいませ (welcome) and thanks you with ありがとうございました.',
        [X('これは いくらですか。', 'これは いくらですか。', 'How much is this?', 1),
          X('いらっしゃいませ！', 'いらっしゃいませ！', 'Welcome!', 1)]),
    ],
    vocab: ['お茶', 'いくら', 'りんご', '一つ', '二つ', 'ジュース', '買う'],
    practice: { shop: ['tsu'], trains: [7, 0], phrases: ['onegaishimasu', 'sumimasen', 'itadakimasu', 'arigatou'] } },

  { id: 'p1-5', phase: 'p1', title: 'Say what you did yesterday',
    goal: 'Talk about the past: what you did, and what you didn\'t.',
    points: [
      GP('mashita', 'ました: past tense', 'V-ました',
        'Swap ます for ました to put a verb in the past: たべます → たべました (ate).',
        [X('きのう ラーメンを たべました。', 'きのう らーめんを たべました。', 'I ate ramen yesterday.', 1)]),
      GP('masen-deshita', 'ませんでした: "didn\'t"', 'V-ませんでした',
        'The past negative is ません plus でした. は after a time word adds "…at least not then".',
        [X('きのうは はしりませんでした。', 'きのうは はしりませんでした。', "I didn't run yesterday.", 1)]),
      GP('deshita', 'でした: "was"', 'N でした',
        'でした is the past of です: きょうは テストです (today is a test), きのうは テストでした (yesterday was a test).',
        [X('きのうは テストでした。', 'きのうは てすとでした。', 'Yesterday was a test.')]),
      GP('mashita-ka', 'Asking about the past', 'なにを V-ましたか。',
        'Add か to a past verb to ask about it. When a question word like だれ is the subject, it takes が.',
        [X('なにを たべましたか。', 'なにを たべましたか。', 'What did you eat?', 2),
          X('レンが かちました！', 'れんが かちました！', 'Ren won!')]),
    ],
    vocab: ['昨日', 'テスト', '見る', 'する', '朝'],
    practice: { trains: [9, 0], story: { chapter: 'ch4', from: 2, to: 6 }, phrases: ['wakarimashita'] } },

  { id: 'p1-6', phase: 'p1', title: 'Describe people and things',
    goal: 'Describe things with い and な adjectives, and say what they are not.',
    points: [
      GP('i-adj', 'い adjectives', 'N は Adj-い です',
        'Most describing words end in い: つよい (strong), はやい (fast), さむい (cold). Put です after them to be polite.',
        [X('きょうは さむいです。', 'きょうは さむいです。', "It's cold today.")]),
      GP('adj-noun', 'Adjective before a noun', 'Adj N',
        'An adjective goes right before the noun it describes, with nothing in between: つよい ライバル (a strong rival).',
        [X('いい 目だ。', 'いい めだ。', 'You have good eyes.', 2),
          X('つよい ライバルだ。', 'つよい らいばるだ。', "He's a strong rival.", 2)]),
      GP('na-adj', 'な adjectives', 'Adj な N / N は Adj です',
        'Some describing words take な before a noun: げんきな ねこ (a lively cat), すきな もの (a thing I like). Before です they drop it.',
        [X('げんきな ねこです。', 'げんきな ねこです。', "It's a lively cat.")]),
      GP('adj-neg', 'Saying "not"', 'Adj-くないです / Adj じゃないです',
        'An い adjective swaps い for くない: さむい → さむくないです. A な adjective adds じゃないです. いい is irregular: よくないです.',
        [X('きょうは さむくないです。', 'きょうは さむくないです。', "It isn't cold today.", 1)]),
    ],
    vocab: ['寒い', '強い', '速い', 'いい', '元気', '大きい', '小さい'],
    practice: { trains: [6, 1], story: { chapter: 'ch4', from: 3, to: 7 }, phrases: ['daijoubu', 'hashi_chopsticks', 'hashi_bridge'] } },

  { id: 'p1-7', phase: 'p1', title: 'Say what\'s where',
    goal: 'Say what is in a place, and where people and things are.',
    points: [
      GP('arimasu', 'あります: there is (things)', 'N が あります',
        'あります says a thing exists or is there. Use it for objects, plants and events.',
        [X('かばんが あります。', 'かばんが あります。', "There's a bag.")]),
      GP('imasu', 'います: there is (people, animals)', 'N が います',
        'います is the same idea for anything alive that moves by itself: people and animals.',
        [X('ねこが います。', 'ねこが います。', "There's a cat.")]),
      GP('ni-exist', 'に: the place where something is', 'Place に N が あります / N は Place に います',
        'に marks where something is. Start with the place to say what is there, or start with the thing and は to say where it is. Actions take で, being somewhere takes に.',
        [X('へやに テレビが あります。', 'へやに てれびが あります。', "There's a TV in the room."),
          X('師匠は 道場に います。', 'ししょうは どうじょうに います。', 'The Master is at the dojo.', 1)]),
      GP('position', 'うえ・した・なか: on, under, in', 'N の した に …',
        'Position words are nouns: "the under-side of the chair" is いすの した. Add に to say something is there.',
        [X('いすの 下に ねこが います。', 'いすの したに ねこが います。', "There's a cat under the chair.")]),
    ],
    vocab: ['ある', 'いる', '椅子', '上', '下', '中', 'テレビ'],
    practice: { trains: [3, 2], story: { chapter: 'ch2', from: 0, to: 3 }, phrases: ['neko', 'inu'] } },

  { id: 'p1-8', phase: 'p1', title: 'Count things and tell the time',
    goal: 'Count things with the right counter and say what time you do things.',
    points: [
      GP('tsu', '～つ: counting small things', 'ひとつ・ふたつ・みっつ…',
        'The native counter ～つ works for most small things from 1 to 9: ひとつ, ふたつ, みっつ, よっつ, いつつ.',
        [X('おにぎりを みっつ ください。', 'おにぎりを みっつ ください。', 'Three rice balls, please.', 3)]),
      GP('hon-mai', '本 and 枚: long things and flat things', 'いっぽん・にほん / いちまい・にまい',
        '本 (ほん, ぼん or ぽん) counts long, thin things like bottles and skewers. 枚 (まい) counts flat things like tickets and crackers.',
        [X('ジュースを にほん ください。', 'じゅーすを にほん ください。', 'Two bottles of juice, please.', 3),
          X('チケットを にまい ください。', 'ちけっとを にまい ください。', 'Two tickets, please.', 3)]),
      GP('ji-ni', '～じに: at a time', '七時に V-ます',
        'Clock times end in じ, and the particle に means "at": しちじに (七時に) is at 7 o\'clock. Watch the special readings: よじ (4), しちじ (7), くじ (9).',
        [X('あさ 七時に おきます。', 'あさ しちじに おきます。', 'I get up at seven in the morning.', 1)]),
      GP('nanji', 'なんじ: "what time?"', 'いま なんじですか。',
        'Put なん in front of a counter to ask "how many" or "what": なんじ (what time), なんぼん (how many bottles).',
        [X('いま なんじですか。', 'いま なんじですか。', 'What time is it now?', 1)]),
    ],
    vocab: ['一つ', '二つ', '三つ', '今', '起きる', '朝'],
    practice: { shop: ['tsu', 'hon', 'mai'], trains: [8] } },

  { id: 'p1-9', phase: 'p1', title: 'Ask who, what, where and when',
    goal: 'Ask simple questions with question words.',
    points: [
      GP('dare', 'だれ: "who"', 'N は だれですか。',
        'だれ asks "who". あの 人 (that person over there) is a polite way to point at someone.',
        [X('あの 人は だれですか。', 'あの ひとは だれですか。', 'Who is that person?', 1)]),
      GP('qword-ga', 'Question words take が', 'だれが / なにが …か。',
        'A question word as the subject always takes が, never は. The answer keeps the が: レンが かちました.',
        [X('だれが かちましたか。', 'だれが かちましたか。', 'Who won?')]),
      GP('doko', 'どこ: "where"', 'N は どこですか。',
        'どこ asks "where". The answer swaps どこ for the place: えきは あそこです (the station is over there).',
        [X('えきは どこですか。', 'えきは どこですか。', 'Where is the station?', 1)]),
      GP('itsu', 'いつ: "when"', 'N は いつですか。',
        'いつ asks "when". Like other time words it needs no particle.',
        [X('しょうぶは いつですか。', 'しょうぶは いつですか。', 'When is the showdown?', 1),
          X('なにを のみますか。', 'なにを のみますか。', 'What will you drink?', 2)]),
    ],
    vocab: ['誰', '何', 'どこ', 'いつ', '人', '駅'],
    practice: { trains: [9, 10, 5], story: { chapter: 'ch1', from: 3, to: 5 }, phrases: ['sumimasen'] } },

  { id: 'p1-10', phase: 'p1', title: 'Say what you want, and ask for help',
    goal: 'Say what you want to do, ask people to do things and invite them along.',
    points: [
      GP('tai', '～たい: "want to"', 'V-stem たいです',
        'Drop ます and add たい: たべます → たべたい (want to eat). It acts like an い adjective, so its negative is たくない.',
        [X('ラーメンが たべたいです。', 'らーめんが たべたいです。', 'I want to eat ramen.', 1)]),
      GP('te-form', 'The て form', 'たべる → たべて / まつ → まって',
        'The て form links verbs to other words. る verbs swap る for て (たべて). Others change by ending: う・つ・る → って, む・ぶ・ぬ → んで, く → いて, す → して. いく → いって, する → して, くる → きて.',
        [X('ちょっと まって ください。', 'ちょっと まって ください。', 'Wait a moment, please.', 1)]),
      GP('te-kudasai', '～てください: "please do"', 'V-て ください。',
        'て form plus ください asks someone to do something, politely. (いって can be "go" or "say"; context tells you which.)',
        [X('もう一度 いって ください。', 'もういちど いって ください。', 'Please say it once more.', 1)]),
      GP('masenka', '～ませんか / ～ましょう: invitations', 'V-ませんか。 / V-ましょう！',
        '～ませんか ("won\'t you…?") is a gentle invitation. ～ましょう means "let\'s…!"',
        [X('いっしょに ラーメンを たべませんか。', 'いっしょに らーめんを たべませんか。', 'Shall we eat ramen together?', 1),
          X('いきましょう！', 'いきましょう！', "Let's go!", 2)]),
    ],
    vocab: ['待つ', '言う', 'ちょっと', '一緒に', '美味しい', '食べる'],
    practice: { trains: [3, 4, 11], story: { chapter: 'ch1', from: 1, to: 3 }, phrases: ['onegaishimasu', 'wakarimashita'] } },

  // ---------------- Phase 2: N4 bridge (outline; content comes later) ----------------
  { id: 'p2-1', phase: 'p2', outline: true, title: 'Say what you\'re doing right now',
    goal: 'Describe ongoing actions and states.', planned: ['～ています (ongoing)', '～ています (state: けっこんしています)', 'て form to chain actions'] },
  { id: 'p2-2', phase: 'p2', outline: true, title: 'Talk like an anime character',
    goal: 'Understand plain, casual speech.', planned: ['Dictionary form', 'ない form', 'た form', 'Casual questions without か'] },
  { id: 'p2-3', phase: 'p2', outline: true, title: 'Give reasons',
    goal: 'Say why, and join two ideas.', planned: ['～から (because)', '～けど / ～が (but)', '～ので'] },
  { id: 'p2-4', phase: 'p2', outline: true, title: 'Compare things',
    goal: 'Say which is stronger, faster or better.', planned: ['A は B より', 'A の ほうが', 'いちばん', 'どちら'] },
  { id: 'p2-5', phase: 'p2', outline: true, title: 'Say what you can do',
    goal: 'Talk about abilities and skills.', planned: ['Potential form (たべられる)', '～ことが できる', 'が with ability'] },
  { id: 'p2-6', phase: 'p2', outline: true, title: 'Ask permission, set rules',
    goal: 'Ask if something is OK and say what must or mustn\'t be done.', planned: ['～ても いい', '～ては いけない', '～なければ ならない'] },
  { id: 'p2-7', phase: 'p2', outline: true, title: 'Talk about plans',
    goal: 'Say what you intend or are going to do.', planned: ['Volitional ～よう / ～おう', '～つもり', '～と おもう'] },
  { id: 'p2-8', phase: 'p2', outline: true, title: 'Talk about experiences',
    goal: 'Say what you have done before.', planned: ['～た ことが ある', '～たり ～たり する', '～た あとで / ～る まえに'] },
];

export const UNIT_BY_ID = Object.fromEntries(UNITS.map((u) => [u.id, u]));
/** Units with full content, in course order. */
export const STUDY_UNITS = UNITS.filter((u) => !u.outline);

/** Every example sentence in the course (for clips, readings and tests). */
export const COURSE_EXAMPLES = STUDY_UNITS.flatMap((u) => u.points.flatMap((p) => p.examples));
