// Picture mnemonics for the Garden's needs-help panel (js/modes/garden.js): one short, original English image per
// Garden word, linking its sound (in romaji capitals) to its meaning. English only, so no voice clips are needed.
// Keyed by Garden id (data.js GARDEN_CATALOG).
export const MNEMONICS = {
  "arigatou": "ARIGATOU → 'ALLIGATOR': you thank the alligator who just carried you across the river on its back.",
  "ohayou": "OHAYOU → 'OHIO': the sun rises over an Ohio cornfield and you shout good morning.",
  "konnichiwa": "KONNICHIWA → 'CONNIE CHEW WA(ter)': Connie waves hello while chewing on a water bottle.",
  "konbanwa": "KONBANWA → 'CON BAN WAR': at dusk a con artist is banned from the war; everyone says good evening.",
  "sayounara": "SAYOUNARA → 'SAY YO, NARA': you say 'yo' to the deer of Nara as you wave goodbye from the train.",
  "sumimasen": "SUMIMASEN → 'SUMO MASON': a sumo mason bumps into you and bows: excuse me, sorry!",
  "itadakimasu": "ITADAKIMASU → 'EAT A DUCK, I MUST': hands together, the hungry hero declares it before a feast.",
  "hajimemashite": "HAJIME MASHITE → 'HAJI ME MASHED': first meeting, you shake hands so hard you mash them. Nice to meet you!",
  "wakarimashita": "WAKARIMASHITA → 'WALK A REAL MAP': the sensei hands you a real map; you nod: got it!",
  "onegaishimasu": "ONEGAISHIMASU → 'OWN A GUY'S SHE-MOOSE': you politely beg, please, can I pet your moose?",
  "daijoubu": "DAIJOUBU → 'DIE? JOE? BOO!': Joe gets punched, jumps up and shouts: I'm fine, it's okay!",
  "nihon": "NIHON → 'KNEE HONE': a samurai hones his knee guard under Japan's rising sun.",
  "toukyou": "TOUKYOU → 'TOE KYO': a giant stubs his TOE on Tokyo Tower and yells KYO!",
  "sensei": "SENSEI → 'SENSE A': the teacher can SENSE an A paper from across the dojo.",
  "gakusei": "GAKUSEI → 'GOCK, YOU SAY?': a student gawks 'GOCK!' at the pop quiz.",
  "mizu": "MIZU → 'ME ZOO': at ME ZOO the elephant sprays everyone with water.",
  "neko": "NEKO → NECK-O: a cat curled around your NECK like a scarf.",
  "inu": "INU → 'IN YOU': a puppy jumps IN YOUr arms.",
  "hashi_chopsticks": "HASHI (high first, HA-shi) → 'HAH! SHE...': she snatches the flying fly with chopsticks. HAH!",
  "hashi_bridge": "HASHI (rising, ha-SHI) → 'HUSH, SHE...': hush, she sneaks across a rope bridge over a canyon.",
  "ame_rain": "AME (A-me) → 'AH, MAY': ah, May showers! Rain pours on the training ground.",
  "ame_candy": "AME (a-ME) → 'AH, MMM': a hard candy pops in your mouth. Ahh, mmm!",
  "hana_flower": "HANA (rising, ha-NA) → 'HAN, NAH': Han offers a flower; it blooms into a giant sunflower.",
  "hana_nose": "HANA (flat) → 'HONK-A': you HONK your nose like a clown's horn.",
  "w:小さい": "CHIISAI → 'CHEESE EYE': a tiny mouse peers through a small hole in the cheese.",
  "w:町": "MACHI → 'MATCH-y': every rooftop in town is lit like a MATCH at the festival.",
  "w:おれ": "ORE → 'OH, RAY!': the cocky hero points at himself: it's ME, Ray!",
  "w:強い": "TSUYOI → 'SUE, YO, EH?': Sue lifts a truck one-handed. Strong, yo!",
  "w:だれ": "DARE → 'DARE-devil': a masked daredevil appears. WHO is that?",
  "w:よろしくおねがいします": "YOROSHIKU ONEGAISHIMASU → 'YO, ROSY CUE': Rosy bows to her new team: please treat me well!",
  "w:目": "ME → 'MEH': a giant eye rolls: meh.",
  "w:明日": "ASHITA → 'A SHEET, AH': you lay out a sheet tonight for tomorrow's picnic.",
  "w:修行": "SHUGYOU → 'SHOE GYO(za)': training under a waterfall wearing shoes stuffed with gyoza.",
  "w:師匠": "SHISHOU → 'SHE SHOW': the old master SHE SHOWs you the secret move.",
  "w:つぎ": "TSUGI → 'SUE GEE': Sue says 'Gee, NEXT!' and calls the next challenger up.",
  "w:あさ": "ASA → 'A SAW': in the morning a rooster saws through your alarm clock.",
  "w:おまえ": "OMAE → 'OH MY!': the rival points rudely: Oh my, YOU again?",
  "w:いちばん": "ICHIBAN → 'ITCHY BAN': #1 champion holds a giant foam finger, itchy from the ban on scratching.",
  "w:ほんとう": "HONTOU → 'HONEST TOE': swear on your honest toe: it's TRUE, really!",
  "w:しょうぶ": "SHOUBU → 'SHOW BOO': two fighters face off in a showdown; the crowd shouts BOO!",
  "w:まける": "MAKERU → 'MAKE A RUE': you lose the match and make a rueful face.",
  "w:まだまだ": "MADAMADA → 'MADAM, MADAM': the Madam sensei wags a finger twice: not yet, still a long way!",
  "w:毎日": "MAINICHI → 'MY KNEE ITCHY': every single day, my knee is itchy.",
  "w:はしる": "HASHIRU → 'HUSH, SHE RUNS': hush, she runs so fast her footsteps are silent.",
  "w:すこしずつ": "SUKOSHI ZUTSU → 'SCOOP SHE ZOOTS': she scoops sand into a bucket, little by little.",
  "w:つかれる": "TSUKARERU → 'SUE CARRY RUE': Sue carries a sack and gets tired, full of rue.",
  "w:休む": "YASUMU → 'YA, SUE, MOO': Sue rests in a hammock beside a dozing cow. Moo.",
  "w:一か月": "IKKAGETSU → 'ICKY GETS': one month of leftovers in the fridge, and it gets icky.",
  "w:もう一度": "MOU ICHIDO → 'MORE, ITCHY DOUGH': knead the itchy dough once more!",
  "w:来る": "KURU → 'COO-ROO': a pigeon coos 'COO-ROO' as it comes flying to you.",
  "w:今日": "KYOU → 'CUE': today is your cue! The spotlight hits you right now.",
  "w:二人": "FUTARI → 'FOOT TARRY': two people tarry, tied foot to foot in a three-legged race.",
  "w:たたかう": "TATAKAU → 'TA-TA-COW': you fight a kung-fu cow; punches go TA-TA-TA!",
  "w:はやい": "HAYAI → 'HIGH EYE': so fast your eyes fly up high just to follow him.",
  "w:かつ": "KATSU → 'CUTS': the hero CUTS through the boss's armor and wins.",
  "w:でも": "DEMO → 'DEMO': the game DEMO looked great... BUT the full game crashed.",
  "w:ライバル": "RAIBARU → 'RIVAL': your RIVAL smirks across the arena, fists ready.",
  "w:ポスター": "POSUTAA → 'POSTER': a giant POSTER of your favourite hero on the wall.",
  "w:大会": "TAIKAI → 'TIE KITE': at the big tournament every fighter ties a kite to their belt.",
  "n5:たくさん": "TAKUSAN → 'TACO SAND': a LOT of tacos, piled as high as a sand dune.",
  "n5:出る": "DERU → 'DARE YOU': I dare you to leave the house in a cape.",
  "n5:お金": "OKANE → 'OH, CANE!': grandpa's cane spills coins - it's full of money!",
  "n5:いる": "IRU → 'EEL ROO': an eel and a kangaroo exist side by side in the aquarium.",
  "w:ない": "NAI → NIGH-ON EMPTY: you open the fridge... there is nothing. NAI!",
  "n5:働く": "HATARAKU → 'HOT TRUCK': you work all day hauling boxes into a hot truck.",
  "n5:隣": "TONARI → 'TOE NARY': your neighbor next door wiggles a toe through the fence.",
  "w:さがす": "SAGASU → 'SAGA SUE': Sue's whole saga is looking for her lost sword.",
  "w:がんばる": "GANBARU → 'GUN BAR': the hero grips the iron bar, hanging in there, doing their best.",
  "n5:待つ": "MATSU → 'MATS': you wait and wait, sitting on the mats until your legs go numb.",
  "w:だんご": "DANGO → 'DANG, GO!': dang, the skewer of rice dumplings goes flying - catch it!",
  "w:ちょうだい": "CHOUDAI → 'CHOW, DIE-hard': a kid reaches out: gimme that chow!",
  "w:うまい": "UMAI → 'OOH, MY!': one bite of ramen and the brawler says: ooh my, tasty!",
  "w:ください": "KUDASAI → 'COULD I SIGH?': you sigh at the counter: please give me that one.",
  "w:おう": "OU → 'OH!': the tough guy grunts 'OH!' with a thumbs up: yeah!",
  "w:ていねい": "TEINEI → 'TAY NAY': a careful butler polishes each spoon, politely saying nay to dust.",
  "n5:いらっしゃいませ": "IRASSHAIMASE → 'EAR, ASSHAI, MASSAGE': shop staff shout a welcome so loud your ears need a massage.",
  "n5:言葉": "KOTOBA → 'COAT O' BAR': words fly out of your coat pocket at the bar like birds.",
  "w:力": "CHIKARA → 'CHICK CARRY': a tiny chick carries a boulder. What power!",
  "w:たまる": "TAMARU → 'TOMORROW': coins pile up in your piggy bank, saved for tomorrow.",
  "n5:多い": "OOI → 'OH-EE!': so many puppies pour in that you squeal OH-EE!",
  "w:こわい": "KOWAI → 'COW WHY?': a giant zombie cow at your window. Why?! Scary!",
  "w:しんぱん": "SHINPAN → 'SHIN PAN': the referee bangs a pan on his shin to stop the fight.",
  "w:一回戦": "IKKAISEN → 'ICKY SEN': the first round is icky: you slip on a banana right away.",
  "w:はじめ": "HAJIME → 'HAH, JUMP!': the referee chops the air: HAH! Begin! Fighters jump in.",
  "w:あいて": "AITE → 'EYE TAY': you lock eyes with your opponent across the ring.",
  "n5:大きい": "OOKII → 'OH, KEY!': oh, a key the size of a car! Big!",
  "w:かち": "KACHI → 'KA-CHING!': victory! The prize machine goes KA-CHING.",
  "w:決勝": "KESSHOU → 'KEG SHOW': the final match is held on top of a giant keg in a big show.",
  "n5:夜": "YORU → 'YOUR ROO': your kangaroo hops under the moon at night.",
  "n5:練習": "RENSHUU → 'RAIN SHOE': practice kicks in the rain until your shoes are soaked.",
  "n5:どうして": "DOUSHITE → 'DOUGH, SHE TAY?': why is she covered in dough? WHY?",
  "w:お久しぶり": "OHISASHIBURI → 'OH, HI, SASHI BURRITO': old friend returns with a burrito: it's been so long!",
  "w:むかし": "MUKASHI → 'MOO CASHEW': long ago, cows paid for everything in cashews.",
  "n5:話": "HANASHI → 'HA, NASHI pear': grandpa tells a story while peeling a nashi pear. Ha!",
  "w:ぬく": "NUKU → NOOK: you pull the sword out of a stone NOOK, then let your shoulders drop and relax.",
  "n5:忘れる": "WASURERU → 'WAS SURE RULE': I was sure of the rule... and then forgot it.",
  "n5:前": "MAE → 'MY': my hero stands right in FRONT of me, before the battle.",
  "w:ねむる": "NEMURU → 'NEMO RULE': Nemo rules: sleep in the anemone all day.",
  "w:こそ": "KOSO → 'CO-SO!': YOU, of all people! A spotlight swings to you with a big KO-SO!",
  "w:ずっと": "ZUTTO → 'ZOOT!': the train goes ZOOOT the whole time, all along the track.",
  "n5:一人": "HITORI → 'HEAT, TORI': one person alone on a hot island, roasting tori (chicken).",
  "n5:楽しい": "TANOSHII → 'TAN, OH SHE...': she gets a tan at the water park. So fun!",
  "w:手かげん": "TEKAGEN → TECH AGAIN: the champ beats you with one finger on the tech again - he is going easy.",
  "w:あたりまえ": "ATARIMAE → 'AT ARMY, EH': of course the army runs at dawn. Natural!",
  "w:本気": "HONKI → 'HONKY': the rival's eyes glow, a truck horn HONKS - now he's serious!",
  "w:わらう": "WARAU → 'WAH-ROW': the whole rowing crew laughs WAH-HA-HA!",
  "n5:手": "TE → TAY: a giant hand waves hello, writing TAY in the sky with one finger.",
  "w:ふるえる": "FURUERU → 'FOOL WAIL': the fool wails and his knees shake and tremble.",
  "w:から": "KARA → 'CAR, AH': because the car broke down, I'm late. Ah!",
  "w:たのしむ": "TANOSHIMU → 'TAN, OH SHE MOO': she enjoys tanning at the farm while cows moo.",
  "n5:もう": "MOU → 'MOW': you already mowed the lawn before breakfast.",
  "n5:行ってきます": "ITTEKIMASU → 'EAT TEA, KISS': eat, drink tea, kiss mom goodbye: I'm off!",
  "w:対": "TAI → 'TIE': Red VS Blue, the score is a TIE.",
  "n5:行く": "IKU → EEK, COO!: a pigeon squeaks EEK and goes, flying off with a COO.",
  "w:パンチ": "PANCHI → 'PUNCH-EE': a giant PUNCH lands with a squeaky EE!",
  "w:より": "YORI → 'YO, REE!': yo, Ree is taller THAN you by a head.",
  "w:じゃねえ": "JANEE → 'JA, NAY!': the punk shakes his head: 'Ja? NAY! That isn't it!'",
  "n5:軽い": "KARUI → 'CAR, WE': this car is so light WE can lift it.",
  "w:全力": "ZENRYOKU → 'ZEN, YO, COO': from zen calm to all-out power - full strength!",
  "w:きまる": "KIMARU → KEY MARU: the judge turns a giant KEY in the scoreboard - it is decided!",
  "w:しょうしゃ": "SHOUSHA → 'SHOW, SHAH': the winner raises the trophy on the show stage like a shah.",
  "w:すごい": "SUGOI → 'SO GOOEY': the hero's final attack is SO GOOEY and huge the crowd screams 'AMAZING!'",
  "w:ぜったい": "ZETTAI → 'SET TIE': the hero SETs his headband TIE tight: 'I will ABSOLUTELY win!'",
  "w:いつでも": "ITSUDEMO → 'IT'S THE DEMO': the free game DEMO you can play ANY TIME you like.",
  "n5:顔": "KAO → 'COW': a COW squishes its huge FACE right up against the camera lens.",
  "w:これから": "KOREKARA → 'CORE CAR': the hero revs the CORE CAR engine: FROM NOW ON, no turning back!",
  "n5:入る": "HAIRU → 'HIGH ROOF': you ENTER the dojo by crashing in through the HIGH ROOF.",
  "w:道場": "DOUJOU → 'DOUGH JOE': JOE kneads DOUGH between sparring rounds at his DOJO.",
  "w:ようこそ": "YOUKOSO → 'YO! COZY, SO come in!': a grinning host waves you into a warm, cozy WELCOME.",
  "k:休": "YASUMU → 'YA, SUMO': a SUMO wrestler flops under a tree to REST. Shape: a person leaning on a tree.",
  "k:明": "ASHITA → 'A SHEET A': pull the SHEET over your head, see you TOMORROW. Shape: sun + moon.",
  "k:林": "HAYASHI → 'HIYA, SHE': two trees side by side; 'HIYA!' SHE yells, leaping through the GROVE.",
  "k:森": "MORI → 'MORE-EE': three trees = MORE trees = a whole FOREST.",
  "k:男": "OTOKO → 'OH, TOUGH GO': a MAN drags a plow, a tough go. Shape: rice field over power.",
  "k:好": "SUKI → 'SKI': you LIKE to SKI. Shape: a woman hugging a child she adores.",
  "k:町": "MACHI → 'MATCHY': every house in TOWN is matchy-matchy. Shape: a field beside a street.",
  "k:体": "KARADA → 'CAR RADAR': a scanner sweeps like CAR RADAR over the hero's whole BODY.",
  "k:岩": "IWA → 'EEE-WAH!': you punch a giant ROCK: EEE-WAH! Shape: mountain over stone.",
  "k:間": "JIKAN → 'GEE, CAN...': a soda CAN timer ticks down your TIME. Shape: sun shining through a gate.",
  "k:聞": "KIKU → 'KICK YOU': I HEAR you sneaking up, so I KICK YOU. Shape: an ear at the gate.",
  "k:話": "HANASU → 'HAN, NASA': HAN SPEAKS over the radio to NASA. Shape: words + tongue.",
  "n5:私": "WATASHI → 'WHAT, A SHE?': no, it's ME! The hero jabs a thumb at their own chest.",
  "n5:あなた": "ANATA → 'AN OTTER': you point at AN OTTER on the rocks: 'YOU there!'",
  "n5:人": "HITO → 'HIT O': one PERSON lands a big HIT on the punching bag.",
  "n5:男": "OTOKO → 'OATS GO': a burly MAN hurls a sack of OATS and roars 'GO!'",
  "n5:女": "ONNA → 'ON A': a WOMAN warrior leaps ON A dragon's back.",
  "n5:子供": "KODOMO → 'CODE DOMO': a tiny CHILD genius cracks the CODE and cheers 'DOMO!'",
  "n5:男の子": "OTOKONOKO → 'OTTO, KNOCK KNOCK': little BOY Otto knocks on the dojo door to train.",
  "n5:女の子": "ONNANOKO → 'ON A KNOCKOUT': a little GIRL wins the tournament ON A KNOCKOUT.",
  "n5:友達": "TOMODACHI → 'TOM O' DOUGH-CHEESE': TOM shares his cheesy DOUGH snack, what a FRIEND.",
  "n5:先生": "SENSEI → 'SENSE SAY': your TEACHER can SENSE what you'll SAY before you say it.",
  "n5:学生": "GAKUSEI → 'GAWK, YOU SAY?': the STUDENT gawks at the board: 'What did you say?'",
  "n5:名前": "NAMAE → 'NAME, EH?': 'Your NAME, eh?' the rival sneers before the duel.",
  "n5:これ": "KORE → 'CORE': you hold up a glowing power CORE: THIS one, right in my hand.",
  "n5:それ": "SORE → 'SORE': THAT bruise on YOUR arm looks SORE. (Near you.)",
  "n5:あれ": "ARE → 'ARRAY': look at THAT ARRAY of stars way OVER THERE.",
  "n5:どれ": "DORE → 'DOOR, EH?': three DOORs. WHICH one hides the boss?",
  "n5:ここ": "KOKO → 'COCOA': the hot COCOA is right HERE in my hands.",
  "n5:そこ": "SOKO → 'SOCK-O': your stinky SOCK is THERE, right next to you.",
  "n5:あそこ": "ASOKO → 'A SOCK, O...': a lone SOCK flaps on a mountaintop way OVER THERE.",
  "n5:どこ": "DOKO → 'DOCK-O?': WHERE is the ship? Not at the DOCK!",
  "n5:この": "KONO → 'CONE-O': THIS ice cream CONE in my hand. Always followed by a noun.",
  "n5:その": "SONO → 'SO, NO...': THAT sword of yours? So... no thanks. Always + a noun near you.",
  "n5:あの": "ANO → 'ANNO-ying': THAT annoying crow over there. Always + a noun far away.",
  "n5:どの": "DONO → 'DON'T KNOW': WHICH sword? I DON'T KNOW! Always + a noun.",
  "n5:何": "NANI → 'NANNY?!': 'WHAT?!' the hero yells as his NANNY blocks his punch.",
  "n5:誰": "DARE → 'DARE': WHO DARES challenge me? A masked figure steps forward.",
  "n5:いつ": "ITSU → 'IT SOON?': WHEN is IT? SOON! The hero checks the countdown.",
  "n5:どう": "DOU → 'DOUGH': HOW do you make DOUGH? The baker just shrugs.",
  "n5:いくら": "IKURA → 'EEK, CURRENCY!': 'EEK! HOW MUCH?!' you gasp at the price tag.",
  "n5:いくつ": "IKUTSU → 'EEK, COOTS!': HOW MANY ducks are in the pond? Count them all!",
  "n5:はい": "HAI → 'HI!': a student shoots a hand up high: 'HI! YES, sensei!'",
  "n5:いいえ": "IIE → 'EE-EH...': you wince 'EE-EH' and shake your head: NO.",
  "n5:ええ": "EE → 'EHH': a lazy 'EHH' with a nod: YEAH, sure.",
  "n5:家族": "KAZOKU → 'CAR ZOO, COOL': the whole FAMILY piles into the CAR for the ZOO. COOL!",
  "n5:父": "CHICHI → 'CHEE-CHEE': a monkey on MY FATHER's shoulder goes CHEE-CHEE.",
  "n5:母": "HAHA → 'HA HA!': MY MOTHER laughs 'HA HA!' at my terrible jokes.",
  "n5:お父さん": "OTOUSAN → 'OH, TOE, SAN!': 'OH, my TOE!' FATHER yelps, stepping on your toy.",
  "n5:お母さん": "OKAASAN → 'OK, SON': 'OK, SON, dinner time!' MOTHER calls from the kitchen.",
  "n5:兄": "ANI → 'ANY': MY OLDER BROTHER can beat ANY boss in the game.",
  "n5:姉": "ANE → 'ON A...': MY OLDER SISTER is always ON A mission to boss me around.",
  "n5:弟": "OTOUTO → 'OH, TOOT-TOOT': MY little BROTHER blasts his toy horn: TOOT-TOOT!",
  "n5:妹": "IMOUTO → 'EMO TOE': MY little SISTER paints her TOEnails black, full EMO.",
  "n5:お兄さん": "ONIISAN → 'OH, KNEE, SAN': BIG BROTHER drops to one KNEE to help you up.",
  "n5:お姉さん": "ONEESAN → 'ONE, EH?': BIG SISTER snatches the last ONE. Eh? Typical.",
  "n5:兄弟": "KYOUDAI → 'KYO, DICE': two SIBLINGS brawl over who gets to roll the DICE.",
  "n5:両親": "RYOUSHIN → 'RIO SHINE': both PARENTS dance and SHINE at the RIO carnival.",
  "n5:おじいさん": "OJIISAN → 'OH, GEEZ, SAN': 'OH GEEEZ!' GRANDPA groans, rising from his chair. Long JII.",
  "n5:おばあさん": "OBAASAN → 'OH, BAAA': GRANDMA knits a sweater while her sheep goes BAAA. Long BAA.",
  "n5:おじさん": "OJISAN → 'OH, GEE, SON': UNCLE grins 'Oh gee, son!' Short JI, younger than grandpa.",
  "n5:おばさん": "OBASAN → 'OH, BUS, SAN': AUNTIE sprints to catch the BUS. Short BA, unlike grandma.",
  "n5:大人": "OTONA → 'OH, TONNA': ADULTS haul a TON of bills and chores.",
  "n5:皆さん": "MINASAN → 'MINE, A SAN': EVERYONE in the dojo shouts 'MINE!' at the last snack.",
  "n5:自分": "JIBUN → 'GEE, BUN': you eat the whole BUN all by YOURSELF. Gee!",
  "n5:彼": "KARE → 'CURRY': HE cooks spicy CURRY for his date. HE, the BOYFRIEND.",
  "n5:彼女": "KANOJO → 'CANOE, JOE': SHE paddles the CANOE while JOE cheers: his GIRLFRIEND.",
  "n5:一": "ICHI → 'ITCHY': ONE itchy spot. Shape: a single stroke.",
  "n5:二": "NI → 'KNEE': TWO KNEEs. Shape: two lines.",
  "n5:三": "SAN → 'SUN': THREE SUNs blaze in the sky. Shape: three lines.",
  "n5:四": "YON → 'YAWN': a cat YAWNs and flops over with all FOUR legs up.",
  "n5:五": "GO → 'GO!': hold up FIVE fingers, high-FIVE, and GO!",
  "n5:六": "ROKU → 'ROCK YOU': SIX ROCKs come flying at YOU.",
  "n5:七": "NANA → 'NANA': Nana blows out the SEVEN candles on her cake.",
  "n5:八": "HACHI → 'HATCH-EE': an egg HATCHes and an octopus with EIGHT legs pops out.",
  "n5:九": "KYUU → 'CUE': NINE balls lined up for one mighty pool CUE shot.",
  "n5:十": "JUU → 'JUICE': you down TEN glasses of JUICE. Shape: a cross, like Roman X for ten.",
  "n5:百": "HYAKU → 'HYAH, CUT!': a HUNDRED training swings: HYAH! CUT!",
  "n5:千": "SEN → 'CENT': a THOUSAND CENTs spill out of the treasure chest.",
  "n5:万": "MAN → 'MAN': TEN THOUSAND MEN march across the battlefield.",
  "n5:一つ": "HITOTSU → 'HEAT TOAST': ONE slice of HEATed TOAST. Just ONE thing.",
  "n5:二つ": "FUTATSU → 'FOOT TOTS': TWO FOOTprints from TWO little tots.",
  "n5:三つ": "MITTSU → 'MITTS': THREE baseball MITTS for THREE fielders.",
  "n5:四つ": "YOTTSU → 'YACHTS': FOUR YACHTS race across the harbor.",
  "n5:五つ": "ITSUTSU → 'IT SUITS YOU': FIVE rings, one per finger. IT SUITS YOU!",
  "n5:六つ": "MUTTSU → 'MUTTS': SIX scruffy MUTTS chase your bike.",
  "n5:七つ": "NANATSU → 'NANA'S': NANA'S SEVEN cats all want dinner now.",
  "n5:八つ": "YATTSU → 'YA CHEWS': an octopus grabs EIGHT gummy bears, one per leg, and YA, CHEWS them all.",
  "n5:九つ": "KOKONOTSU → 'COCONUTS': NINE COCONUTS stacked in a wobbly pyramid.",
  "n5:十|とお": "TOO → 'TOE': count your TEN TOEs; a kid wiggles them: 'I'm TEN years old!'",
  "n5:二人": "FUTARI → 'FOOT TARRY': TWO PEOPLE tarry, standing FOOT to foot before a duel.",
  "n5:半分": "HANBUN → 'HAM BUN': you slice the HAM BUN in HALF to share.",
  "n5:番号": "BANGOU → 'BANG, GO!': the racer's NUMBER is called: BANG, GO!",
  "n5:今": "IMA → 'I'M A...': 'I'M A hero NOW!' you shout, powering up right NOW.",
  "n5:今日": "KYOU → 'CUE': TODAY is your CUE: step onto the stage.",
  "n5:明日": "ASHITA → 'ASH-TA': a phoenix rises from the ASH, ready to fight again TOMORROW.",
  "n5:昨日": "KINOU → 'KEY, NO!': YESTERDAY you lost your KEY. NO!",
  "n5:毎日": "MAINICHI → 'MY KNEE ITCHY': EVERY DAY MY KNEE is ITCHY.",
  "n5:朝": "ASA → 'AS A...': AS A new MORNING dawns, the hero rises with the sun.",
  "n5:昼": "HIRU → 'HERO': at NOON the HERO eats lunch under the blazing sun.",
  "n5:晩": "BAN → 'BAN': every EVENING, phones are BANned at the dinner table.",
  "n5:夕方": "YUUGATA → 'YOU GOTTA': YOU GOTTA be home by DUSK, before the sun sets.",
  "n5:今朝": "KESA → 'KISSER': THIS MORNING the dog woke you, licking your face like a KISSER.",
  "n5:今晩": "KONBAN → 'CON BAND': TONIGHT the anime CON BAND plays a live show.",
  "n5:午前": "GOZEN → 'GO ZEN': in the A.M. you GO ZEN and meditate at sunrise.",
  "n5:午後": "GOGO → 'GO-GO': in the P.M. you GO-GO dance all afternoon.",
  "n5:時間": "JIKAN → 'GEE, CAN I?': 'Gee, CAN I have more TIME?' the hero begs as the clock hits zero.",
  "n5:時計": "TOKEI → 'TOE, OK': a CLOCK strapped to your TOE says it's OK... nope, you're late!",
  "n5:週": "SHUU → 'SHOE': a WEEK's worth of SHOEs, one pair for each day.",
  "n5:今週": "KONSHUU → 'CON SHOE': THIS WEEK is the anime CON: wear comfy SHOEs.",
  "n5:来週": "RAISHUU → 'RICE SHOE': NEXT WEEK you'll fill your rival's SHOE with RICE.",
  "n5:先週": "SENSHUU → 'SEND SHOE': LAST WEEK you SENT a SHOE by mail. Still waiting.",
  "n5:毎週": "MAISHUU → 'MY SHOE': EVERY WEEK the dog chews MY SHOE.",
  "n5:今月": "KONGETSU → 'GONG GETS YOU': THIS MONTH a giant GONG GETS YOU up every morning.",
  "n5:来月": "RAIGETSU → 'RAY GETS YOU': NEXT MONTH the boss's laser RAY GETS YOU. Train now!",
  "n5:先月": "SENGETSU → 'SEN-sei GETS YOU': LAST MONTH SENsei GOT YOU with a surprise test.",
  "n5:毎月": "MAITSUKI → 'MY SKI': EVERY MONTH I wax MY SKIs.",
  "n5:今年": "KOTOSHI → 'COAT O' SHEEP': THIS YEAR's new winter COAT is made of SHEEP wool.",
  "n5:来年": "RAINEN → 'RAIN, ENDLESS': NEXT YEAR, they say, it will RAIN ENdlessly.",
  "n5:去年": "KYONEN → 'KEY, NEON': LAST YEAR's broken NEON sign still flickers by the KEY shop.",
  "n5:毎年": "MAITOSHI → 'MY TOE, SHE...': EVERY YEAR she steps on MY TOE at the festival dance.",
  "n5:年": "TOSHI → 'TOE, SHE': every YEAR she counts her AGE on her TOEs.",
  "n5:月曜日": "GETSU-YOUBI → 'GET SUE': MONDAY (moon day): GET SUE out of bed while the moon's still up.",
  "n5:火曜日": "KA-YOUBI → 'CAR': TUESDAY (fire day): your CAR bursts into flames!",
  "n5:水曜日": "SUI-YOUBI → 'SWEET': WEDNESDAY (water day): SWEET, it's pool day!",
  "n5:木曜日": "MOKU-YOUBI → 'MOCK YOU': THURSDAY (tree day): the trees MOCK YOU as you walk by.",
  "n5:金曜日": "KIN-YOUBI → 'KING': FRIDAY (gold day): you're KING with a pile of gold.",
  "n5:土曜日": "DO-YOUBI → 'DOUGH': SATURDAY (earth day): squish DOUGH and dirt in the garden.",
  "n5:日曜日": "NICHI-YOUBI → 'NEAT CHEESE': SUNDAY (sun day): NEAT, a CHEESy picnic in the sun.",
  "n5:一昨日": "OTOTOI → 'OH, TOE TOY': THE DAY BEFORE YESTERDAY you stepped on a TOY. TOE still hurts.",
  "n5:明後日": "ASATTE → 'AS A TEAM': THE DAY AFTER TOMORROW we fight AS A TEAM.",
  "n5:毎朝": "MAI-ASA → 'MY, AS A rule...': EVERY MORNING: 'MY! AS A rule, I train at dawn.'",
  "n5:毎晩": "MAI-BAN → 'MY BAN': EVERY NIGHT MY phone gets BANned at bedtime.",
  "n5:誕生日": "TANJOUBI → 'TAN JOE, BE': JOE gets a TAN at his BIRTHDAY beach party.",
  "n5:休み": "YASUMI → 'YA, SUE ME': a HOLIDAY nap in a hammock. 'YA, SUE ME!'",
  "n5:夏休み": "NATSU-YASUMI → 'NUTS, YA SUE ME': SUMMER VACATION, munching NUTS on the beach. Sue me!",
  "n5:春": "HARU → 'HA, ROO!': a kangaroo laughs HA while hopping through spring cherry blossoms.",
  "n5:夏": "NATSU → NUTS: summer heat makes you go NUTS on the beach, sweating buckets.",
  "n5:秋": "AKI → ACHY: raking piles of autumn leaves leaves your back ACHY.",
  "n5:冬": "FUYU → 'FEW YOU': in winter, FEW of YOU dare leave the warm house.",
  "n5:後": "ATO → 'AT OH...': the hero says 'I'll do it later' - AT O'clock never. After!",
  "n5:ご飯": "GOHAN → GO HAN!: Han shouts GO and charges a giant bowl of rice. Meal time!",
  "n5:朝ご飯": "ASA + GOHAN → 'ASAP GOHAN': breakfast eaten ASAP before the morning training run.",
  "n5:昼ご飯": "HIRU + GOHAN → 'HERO GOHAN': the HERO pauses mid-fight at noon for a lunch break.",
  "n5:晩ご飯": "BAN + GOHAN → 'BANG! GOHAN': the dinner gong goes BANG at sunset - evening meal!",
  "n5:食べ物": "TABEMONO → 'TABLE MONO': one MONOlith-sized TABLE piled high with food.",
  "n5:飲み物": "NOMIMONO → 'NOM ME MONO': a drink can begs 'NOM ME!' - any beverage.",
  "n5:水": "MIZU → MISTY: a MISTY waterfall soaks the hero with cold water.",
  "n5:お茶": "OCHA → 'OH CHA!': OH, a cup of green tea; you sip it and go 'CHA!'",
  "n5:お酒": "OSAKE → 'OH, SAKE!': OH, the old master pours a cup of SAKE - adults only.",
  "n5:牛乳": "GYUUNYUU → 'GOO NEW': a cow squirts fresh NEW milk with a GOOey splash.",
  "n5:コーヒー": "KOOHII → COFFEE: say COFFEE with a sleepy yawn - KOH-HEE - steaming mug in hand.",
  "n5:紅茶": "KOUCHA → 'COACH A': the COACH hands A cup of dark black tea to the team.",
  "n5:ジュース": "JUUSU → JUICE: a JUICE box squeezed so hard it sprays orange everywhere.",
  "n5:肉": "NIKU → 'NICK YOU': a hungry dog tries to NICK YOUr meat off the grill.",
  "n5:魚": "SAKANA → 'SOCK, CAN, AH': you fish up a SOCK, a CAN, then AH - a real fish!",
  "n5:野菜": "YASAI → 'YA SIGH': the kid sees vegetables on the plate and goes 'YA...' *SIGH*.",
  "n5:果物": "KUDAMONO → 'COULD A MONO': COULD A MONkey eat this whole fruit basket? Yes.",
  "n5:卵": "TAMAGO → 'TOMORROW GO': the egg will hatch TOMORROW - GO watch it crack!",
  "n5:パン": "PAN → PAN: a loaf of bread baking in a hot PAN.",
  "n5:お菓子": "OKASHI → 'OH, CASH-y': OH, you spent all your CASH on sweets and snacks.",
  "n5:塩": "SHIO → 'SHE OH!': SHE spills salt and goes 'OH!' - throw a pinch over your shoulder.",
  "n5:砂糖": "SATOU → 'SAT ON': you SAT ON a sugar bag and it exploded into sweet dust.",
  "n5:醤油": "SHOUYU → 'SHOW YOU': let me SHOW YOU how to dip sushi in dark soy sauce.",
  "n5:料理": "RYOURI → 'RIO REE': a chef in RIO flips a sizzling dish - cooking with flair!",
  "n5:お弁当": "OBENTOU → 'OH, BENT TOE': OH, you BENT a TOE tripping over your boxed lunch.",
  "n5:牛肉": "GYUU + NIKU → 'GOO NICK YOU': a cow (GYUU) says don't NICK my meat - beef!",
  "n5:豚肉": "BUTA + NIKU → 'BOOTA NICK YOU': a pig in BOOTs guards his pork from you.",
  "n5:鳥肉": "TORI + NIKU → 'TORE-y NICK YOU': a bird (TORI) flaps off - chicken meat stays.",
  "n5:りんご": "RINGO → RING-GO: an apple tossed through a RING - GO! Ringo the apple.",
  "n5:バナナ": "BANANA → BANANA: same word - a hero slips on a BANANA peel mid-battle.",
  "n5:みかん": "MIKAN → 'ME CAN': ME CAN peel a mandarin orange in one spiral!",
  "n5:カレー": "KAREE → CURRY: a giant pot of CURRY, so spicy the hero breathes fire.",
  "n5:バター": "BATAA → BUTTER: a slab of BUTTER melting on hot toast.",
  "n5:お腹": "ONAKA → 'OH, KNOCK-A': OH, KNOCK on your belly - it growls back, hungry stomach!",
  "n5:箸": "HASHI → 'HASH-y': two chopsticks pinching a pile of HASH browns. (Accent differs from bridge.)",
  "n5:皿": "SARA → SARAH: SARAH spins a plate on one finger like a circus pro.",
  "n5:茶碗": "CHAWAN → 'CHOW WAN': CHOW down from ONE (wan) rice bowl.",
  "n5:コップ": "KOPPU → COP: a COP drinks water from a glass after a long chase.",
  "n5:カップ": "KAPPU → CUP: a CUP of hot cocoa, KAPPU, warming your hands.",
  "n5:フォーク": "FOOKU → FORK: a FORK stabbing a meatball, FOH-KU!",
  "n5:ナイフ": "NAIFU → KNIFE: a chef's KNIFE flashing like a samurai blade - NAI-FU!",
  "n5:スプーン": "SUPUUN → SPOON: a SPOON scooping soup - SU-POON!",
  "n5:レストラン": "RESUTORAN → RESTAURANT: a waiter rushes your order at a RESTAURANT - RE-SU-TO-RAN!",
  "n5:食堂": "SHOKUDOU → 'SHOCK, DOUGH!': SHOCK - the school cafeteria served raw DOUGH again.",
  "n5:喫茶店": "KISSATEN → 'KISS A TEN': at the cafe you KISS A TEN-dollar coffee goodbye.",
  "n5:来る": "KURU → 'COO-ROO': a pigeon goes COO-ROO and comes flying to you.",
  "n5:帰る": "KAERU → 'KAY, ROO': 'OK, ROO, go home!' - the kangaroo hops back home.",
  "n5:食べる": "TABERU → 'TABLE-RU': you eat so much you could eat the TABLE too.",
  "n5:飲む": "NOMU → 'NOM MOO': a cow drinks milk going NOM, MOO.",
  "n5:見る": "MIRU → MIRROR: you see and watch yourself in a MIRROR.",
  "n5:聞く": "KIKU → 'KEY COO': put your ear to the KEYhole and listen to a pigeon COO.",
  "n5:話す": "HANASU → 'HAN, NASA': HAN talks nonstop to NASA on the radio.",
  "n5:言う": "IU → \"EE-OO\": a hero says his attack name with a long EE-OO echo.",
  "n5:読む": "YOMU → 'YO, MOO!': a cow reads a manga and says 'YO, MOO, this is good!'",
  "n5:書く": "KAKU → 'COCK-OO': a cuckoo bird writes letters with a quill. KAKU!",
  "n5:買う": "KAU → COW: you buy a whole COW at the market.",
  "n5:売る": "URU → 'OO, ROO': OO! a kangaroo sells stuff from its pouch.",
  "n5:する": "SURU → \"SURE, ROO\": \"SURE!\" says the kangaROO - it will DO anything you ask.",
  "n5:ある": "ARU → 'ARE, ROO': there ARE things here - a treasure chest exists in the cave.",
  "n5:分かる": "WAKARU → 'WALK A ROO': you finally understand how to WALK A kangaROO. Aha!",
  "n5:起きる": "OKIRU → 'OK, EAR-RU': OK, an alarm in your EAR - time to get up!",
  "n5:寝る": "NERU → 'NEAR-ROO': you sleep NEAR a cuddly kangaROO.",
  "n5:会う": "AU → 'OW!': two rivals meet by bumping heads - 'OW!'",
  "n5:持つ": "MOTSU → \"MOAT SUit\": you hold a heavy sword while wading a castle MOAT.",
  "n5:作る": "TSUKURU → 'SUE COO ROO': SUE makes a COOkie shaped like a kangaROO.",
  "n5:使う": "TSUKAU → 'SKA COW': you use a COW as a SKAteboard.",
  "n5:休む": "YASUMU → 'YA, SUE MOO': 'YA, SUE, take time off,' says the cow. Rest!",
  "n5:勉強する": "BENKYOU SURU → 'BEN, CURIO': BEN studies a CURIO all night for the exam.",
  "n5:教える": "OSHIERU → 'OH, SHE ERRS': OH, SHE ERRS - so the sensei teaches her the move.",
  "n5:習う": "NARAU → 'NARROW': you learn the NARROW path from a master, step by step.",
  "n5:覚える": "OBOERU → 'OH, BOY, ERR': OH BOY, don't ERR - memorize the spell!",
  "n5:知る": "SHIRU → 'SHE RULES': SHE knows everything - SHE RULES the quiz show.",
  "n5:思う": "OMOU → 'OH, MOO': a cow thinks deep thoughts - 'OH... MOO.'",
  "n5:始まる": "HAJIMARU → 'HAH, JIM, A ROO': 'HAH! JIM vs A kangaROO - the fight begins!'",
  "n5:終わる": "OWARU → 'OH, WAR': OH, the WAR is over - it ends at last.",
  "n5:開ける": "AKERU → 'ACHE-RU': your arm ACHES as you pry open the treasure chest.",
  "n5:閉める": "SHIMERU → 'SHIMMER': you close the door on a SHIMMERing portal.",
  "n5:開く": "AKU → 'AH, COO': AH, the door opens by itself and a pigeon COOs in.",
  "n5:閉まる": "SHIMARU → \"SHE MARRow\": the shop door slides closed by itself right as SHE arrives. Shut!",
  "n5:歩く": "ARUKU → 'A ROOK': you walk like A chess ROOK - straight lines only.",
  "n5:走る": "HASHIRU → 'HASH-EE-ROO': a kangaROO runs and kicks up HASH browns.",
  "n5:泳ぐ": "OYOGU → 'OH, YOGURT': you swim through a pool of OH, YOGURT?!",
  "n5:遊ぶ": "ASOBU → 'A SO-BOO': kids play peekaboo - 'A SO, BOO!'",
  "n5:歌う": "UTAU → 'OOH, TOW': you sing 'OOH' while a TOW truck drags you off stage.",
  "n5:立つ": "TATSU → TATTOO: the hero stands up tall, flexing a dragon TATTOO.",
  "n5:座る": "SUWARU → 'SUE, WAR': SUE sits down in the middle of a WAR to eat lunch.",
  "n5:乗る": "NORU → 'NO ROO': 'NO ROOm!' - you still ride on the packed train.",
  "n5:降りる": "ORIRU → 'OH, REAL': OH, REALly? You get off at the wrong stop!",
  "n5:着く": "TSUKU → 'SUE COO': SUE arrives at the station to a pigeon's COO.",
  "n5:住む": "SUMU → 'SUMO': a SUMO wrestler lives in your tiny apartment.",
  "n5:死ぬ": "SHINU → 'SHE NEW': the villain dies dramatically... SHE comes back NEW next season.",
  "n5:呼ぶ": "YOBU → 'YO, BOO!': you call out 'YO, BOO!' to invite your buddy over.",
  "n5:答える": "KOTAERU → 'COAT AIR-RU': you answer the quiz from inside a COAT full of AIR.",
  "n5:聞こえる": "KIKOERU → 'KEY CO-AIR': you can hear a KEY jingle carried on the AIR.",
  "n5:見せる": "MISERU → \"ME, SAY RUle\": ME show off my new power-up to the whole squad - look!",
  "n5:貸す": "KASU → 'CASH-oo': you lend your friend CASH, hoping he pays back.",
  "n5:借りる": "KARIRU → 'CARRY ROO': you borrow a kangaROO to CARRY your bags.",
  "n5:返す": "KAESU → 'CASE': you give back the CASE you borrowed - returned!",
  "n5:あげる": "AGERU → 'AH, GAIR': AH, you give a GEAR to your mecha buddy.",
  "n5:もらう": "MORAU → 'MORE OW': you receive MORE presents - OW, they're heavy!",
  "n5:くれる": "KURERU → 'CURE-RU': a healer gives a CURE to me. (Given to me!)",
  "n5:取る": "TORU → TORE: you TORE the last cookie and take it. 'Pass the salt' too.",
  "n5:置く": "OKU → 'OAK COO': you put a pigeon on an OAK branch. COO.",
  "n5:押す": "OSU → 'OSU!': the karate dojo shout OSU! - push the heavy door open.",
  "n5:引く": "HIKU → 'HE COO': HE pulls a rope and a pigeon goes COO.",
  "n5:付ける": "TSUKERU → 'SKATE-RU': attach rockets to your SKATEs and turn them on.",
  "n5:消す": "KESU → 'KISS-oo': blow a KISS to turn off the candle - and erase the board.",
  "n5:点く": "TSUKU → 'SUE COO': SUE flips the switch and the light comes on - a pigeon COOs.",
  "n5:消える": "KIERU → 'KEY AIR': the KEY vanishes into thin AIR - lights go out.",
  "n5:出す": "DASU → \"DUST\": you take out your homework from a DUSTy bag and hand it in.",
  "n5:入れる": "IRERU → 'EAR-RAY': you put a RAY of light IN your EAR. Insert!",
  "n5:送る": "OKURU → 'OH, CORAL': OH, you send a CORAL piece by mail to a friend.",
  "n5:洗う": "ARAU → 'ARROW': you wash the mud off your ARROWs.",
  "n5:浴びる": "ABIRU → 'ABBY ROO': ABBY takes a shower with a kangaROO.",
  "n5:着る": "KIRU → 'KEY ROO': a kangaROO wears a KEY necklace and a jacket.",
  "n5:脱ぐ": "NUGU → 'NEW GOO': take off your clothes - they're covered in NEW GOO!",
  "n5:履く": "HAKU → 'HACK-oo': HACK your feet into shoes and pants in one jump.",
  "n5:被る": "KABURU → 'CAB ROO': a CAB driver kangaROO puts on a hat.",
  "n5:掛ける": "KAKERU → 'CAKE-RU': hang a CAKE on a hook, then make a phone call.",
  "n5:吸う": "SUU → 'SUE': SUE breathes in deep before the big shout.",
  "n5:吹く": "FUKU → 'FOO COO': blow 'FOO!' and a pigeon flies off - COO!",
  "n5:降る": "FURU → 'FOO-ROO': rain and snow fall on a kangaROO - FOO, cold!",
  "n5:晴れる": "HARERU → 'HARE-RU': a HARE hops out as the sky clears up.",
  "n5:曇る": "KUMORU → 'COO MORE': the sky gets cloudy and pigeons COO MORE.",
  "n5:飛ぶ": "TOBU → 'TOE BOO': you kick off with your TOE and fly - BOO-m!",
  "n5:鳴く": "NAKU → 'KNOCK-oo': a bird chirps and KNOCKs on your window.",
  "n5:咲く": "SAKU → 'SACK COO': a flower blooms out of a SACK - COO!",
  "n5:並ぶ": "NARABU → 'NARROW BOO': you line up in a NARROW hall - someone shouts BOO!",
  "n5:並べる": "NARABERU → 'NARROW BELL': you arrange BELLs in a NARROW row.",
  "n5:渡る": "WATARU → 'WATER-ROO': a kangaROO crosses the WATER in one leap.",
  "n5:渡す": "WATASU → 'WATER SUE': you hand over a WATER bottle to SUE.",
  "n5:曲がる": "MAGARU → MAGGOT ROO: a kangaroo drifts its race car to TURN the corner, tires screeching.",
  "n5:困る": "KOMARU → COMMA RUE: a hero stuck mid-sentence on a giant COMMA, totally TROUBLED what to say next.",
  "n5:頼む": "TANOMU → TAN 'N' MOO: you ASK a cow politely for a favour; she nods and ORDERS a tan for you.",
  "n5:弾く": "HIKU → HE COOs: a hero strums his guitar and HE COOs a ballad as he PLAYS the instrument.",
  "n5:撮る": "TORU → TOE-RU: you TAKE A PHOTO with your TOE pressing the shutter mid-flying kick.",
  "n5:切る": "KIRU → KILL-ROPE: a samurai slashes and CUTS the rope in one clean strike.",
  "n5:磨く": "MIGAKU → ME GOT CUE: ME GOT a pool CUE and use it to POLISH and BRUSH my teeth till they sparkle.",
  "n5:生まれる": "UMARERU → OOH MA, RARE ROO: 'Ooh Ma, a RARE ROO!' - a baby kangaroo is BORN in a burst of light.",
  "n5:結婚する": "KEKKON → KECK-CON: two rivals at a fan CON KICK down the door and get MARRIED on stage.",
  "n5:散歩する": "SANPO → SAND PO: a dog named Po strolls through SAND, TAKING A WALK along the beach.",
  "n5:旅行する": "RYOKOU → REAL COKE: you TRAVEL the world on a giant flying bottle of REAL COKE.",
  "n5:掃除する": "SOUJI → SO JEEZ: 'SO JEEZ, this mess!' - a ninja CLEANS the dojo at lightning speed.",
  "n5:洗濯する": "SENTAKU → SEND TACO: you SEND a TACO spinning in the washing machine while DOING LAUNDRY.",
  "n5:料理する": "RYOURI → RIO REE: a chef in RIO yells 'REE!' while COOKING with flaming pans.",
  "n5:練習する": "RENSHUU → RAN SHOE: you RAN until your SHOE smoked - PRACTICING laps all night.",
  "n5:質問する": "SHITSUMON → SHE'S SUMMONING: SHE'S SUMMONING her hand up high to ASK A QUESTION in class.",
  "n5:電話する": "DENWA → DEN WAH: from his DEN a baby cries 'WAH!' into the PHONE to MAKE A CALL.",
  "n5:出かける": "DEKAKERU → DECK A CAKE ROO: you DECK out a CAKE for a ROO, then GO OUT to the party.",
  "n5:疲れる": "TSUKARERU → SUE, CAR RARE: Sue pushes her RARE CAR uphill and GETS TIRED, flopping over.",
  "n5:始める": "HAJIMERU → HA, JIM, RUN!: 'HA, JIM, RUN!' - the starter pistol fires and the race BEGINS.",
  "n5:勤める": "TSUTOMERU → SUE TOE MERRY: SUE works MERRILY at her job, EMPLOYED to paint TOEnails.",
  "n5:登る": "NOBORU → NO BORE: NO BOREdom here - you CLIMB a cliff with a sword in your teeth.",
  "n5:要る": "IRU → EAR ROO: a kangaroo NEEDS a giant EAR trumpet to hear anything.",
  "n5:できる": "DEKIRU → DECK KILL ROO: 'I CAN DO it!' - a hero DECKs a giant ROO in one punch.",
  "n5:なる": "NARU → NARROW: a skinny NARROW sapling powers up and BECOMES a giant tree.",
  "n5:やる": "YARU → YA ROO!: 'YA, ROO, let's DO it!' - a kangaroo casually jumps into action.",
  "n5:違う": "CHIGAU → CHEEK GOW: 'WRONG!' - a sensei taps your CHEEK when your answer is DIFFERENT.",
  "n5:小さい": "CHIISAI → CHEESE EYE: a tiny SMALL mouse peers through a CHEESE hole with one EYE.",
  "n5:新しい": "ATARASHII → AT A RASH, HE: AT A RASH speed HE unboxes his NEW sword, still shining.",
  "n5:古い": "FURUI → FOOL OOEY: an OLD fool's sword is OOEY with rust, cobwebs everywhere.",
  "n5:いい": "II → EEE!: you squeal 'EEE!' with a thumbs up - that's GOOD!",
  "n5:悪い": "WARUI → WALL-WE: a BAD villain smashes WALLs while WE run.",
  "n5:高い": "TAKAI → TALK KITE: a price tag on a TALL KITE so high it's EXPENSIVE to reach.",
  "n5:安い": "YASUI → YA SWEET: 'YA, SWEET deal!' - you grab a CHEAP sword from the bargain bin.",
  "n5:低い": "HIKUI → HE COOEY: HE crouches LOW and short, cooing 'COOEY' under the table.",
  "n5:長い": "NAGAI → NAG GUY: a NAG GUY lectures so LONG his beard grows to the floor.",
  "n5:短い": "MIJIKAI → ME, JEEK, EYE: a SHORT ninja whose cape barely covers ME - JEEK!",
  "n5:少ない": "SUKUNAI → SCOOP NIGH: only a FEW grains left in the SCOOP - nigh empty.",
  "n5:早い": "HAYAI (early) → HI-YAI: you yell 'HI, YA!' at 5 a.m. - way too EARLY for training.",
  "n5:速い": "HAYAI (fast) → HIGH-YAY: a hero zooms past so FAST his hair flies HIGH - 'YAY!'",
  "n5:遅い": "OSOI → OH SOY: 'OH, SOY sauce is SLOW!' - you wait forever for it to drip out. You're LATE.",
  "n5:近い": "CHIKAI → CHICK EYE: a CHICK is so NEAR its EYE presses against your nose.",
  "n5:遠い": "TOOI → TOE-EE: you kick your TOE so hard the ball flies FAR - 'EEE!'",
  "n5:暑い": "ATSUI (weather) → HAT SUE: Sue wears a sun HAT; the summer is so HOT the road melts.",
  "n5:寒い": "SAMUI → SAMURAI: a SAMURAI frozen solid in a COLD blizzard, teeth chattering.",
  "n5:熱い": "ATSUI (touch) → HOT SUE: Sue grabs a pan handle - 'OW, HOT to the touch!' - and drops it.",
  "n5:冷たい": "TSUMETAI → SUE MET ICE: SUE MET an ICE block and touched it - brr, COLD!",
  "n5:暖かい": "ATATAKAI → AT A TACKY: AT A TACKY beach party, the spring sun feels nice and WARM.",
  "n5:涼しい": "SUZUSHII → SUSHI SHE: SHE eats SUSHI in a COOL evening breeze.",
  "n5:ぬるい": "NURUI → NEW RUE: your NEW tea went LUKEWARM while you rued a lost battle.",
  "n5:難しい": "MUZUKASHII → MOOSE-KA-SHE: a MOOSE trying a hard puzzle; SHE says 'DIFFICULT!'",
  "n5:易しい": "YASASHII (easy) → YA, SASHAY: 'YA, so EASY' - you SASHAY through a simple quiz.",
  "n5:優しい": "YASASHII (kind) → YA, SAS-SHE: a GENTLE heroine says 'YA' and SHE heals a hurt puppy.",
  "n5:面白い": "OMOSHIROI → OH MOSH, ROY!: 'OH, MOSH, ROY!' - Roy's FUNNY mosh-pit dance has everyone laughing.",
  "n5:つまらない": "TSUMARANAI → SUE, MA, RAN NIGH: Sue's Ma RAN off - the lecture was so BORING.",
  "n5:嬉しい": "URESHII → OO, RESH-SHE: 'OOH!' SHE squeals, HAPPY, getting a fresh new sword.",
  "n5:悲しい": "KANASHII → CAN, NASTY: a SAD hero's ramen CAN spills - so NASTY, tears fall.",
  "n5:忙しい": "ISOGASHII → EE, SO GASH-SHE: 'EE, SO BUSY!' SHE juggles ten tasks at once.",
  "n5:美味しい": "OISHII → OY, SHE!: 'OY, SHE ate my ramen!' - because it was DELICIOUS.",
  "n5:甘い": "AMAI → AH, MY!: 'AH, MY!' - a candy so SWEET your eyes turn into hearts.",
  "n5:辛い": "KARAI → CAR RYE: a curry so SPICY your mouth shoots fire like a CAR exhaust.",
  "n5:痛い": "ITAI → 'IT, AYE!': you stub your toe - 'IT hurts, AYE!' - so PAINFUL your eyes water.",
  "n5:強い": "TSUYOI → SUE YO-YO: SUE swings a giant YO-YO and smashes a boulder - STRONG!",
  "n5:弱い": "YOWAI → YO, WHY?: 'YO, WHY so WEAK?' - a hero can't even lift a spoon.",
  "n5:重い": "OMOI → OH, MOI!: 'OH, MOI back!' - lifting a HEAVY boulder bends you double.",
  "n5:広い": "HIROI → HERO-EE: the HERO stands in a WIDE, SPACIOUS arena that stretches forever.",
  "n5:狭い": "SEMAI → SEE MY: 'SEE MY room?' - so NARROW and CRAMPED you're squished sideways.",
  "n5:明るい": "AKARUI → A CAR, OOEY: A CAR's headlights so BRIGHT everyone shouts 'OOEY!'",
  "n5:暗い": "KURAI → CRY: a kid CRIES in a DARK cave with no flashlight.",
  "n5:白い": "SHIROI → SHEER-OY: a SHEER WHITE cape billows on the snowy mountaintop.",
  "n5:黒い": "KUROI → CORE-OY: the villain's BLACK CORE pulses with dark energy.",
  "n5:赤い": "AKAI → A KITE: A KITE painted fiery RED swoops across the sky.",
  "n5:青い": "AOI → OW, OY: 'OW, OY!' - you bonk your head and get a BLUE bruise.",
  "n5:黄色い": "KIIROI → KEY ROY: ROY's lucky KEY is bright YELLOW like a banana.",
  "n5:茶色": "CHAIRO → CHAI ROW: a ROW of CHAI cups, all warm BROWN.",
  "n5:緑": "MIDORI → ME DORY: ME and DORY swim through GREEN seaweed.",
  "n5:色": "IRO → EAR-O: paint drips in every COLOUR from a giant EAR.",
  "n5:可愛い": "KAWAII → CAR, WHY?: 'CAR, WHY so CUTE?' - a tiny car with puppy eyes.",
  "n5:若い": "WAKAI → WACKY: a WACKY YOUNG ninja kid flips around the dojo.",
  "n5:太い": "FUTOI → FOOT OY: a FOOT so THICK it cracks the floor - 'OY!'",
  "n5:細い": "HOSOI → HOSE-OY: a THIN, NARROW HOSE squirts a tiny stream - 'OY!'",
  "n5:厚い": "ATSUI (thick) → AT SUE: a THICK book thrown AT SUE bounces off like a brick.",
  "n5:薄い": "USUI → OO, SWEE: tea so WEAK and THIN you go 'OO, SWEE-t water?'",
  "n5:丸い": "MARUI → MARBLE-EE: a ROUND marble rolls across the arena floor.",
  "n5:汚い": "KITANAI → KIT NIGH: your gym KIT is so DIRTY flies circle it.",
  "n5:危ない": "ABUNAI → A BOON, NIGH: 'DANGER!' - A huge BOULDER rolls nigh; dodge!",
  "n5:欲しい": "HOSHII → HOSE SHE: SHE WANTS that shiny fire HOSE so badly she's drooling.",
  "n5:うるさい": "URUSAI → OO, RUSSIA-EYE: 'URUSAI!' - a NOISY rival yells so loud your EYEs rattle.",
  "n5:眠い": "NEMUI → NAME-OOEY: so SLEEPY you forget your NAME and droop onto your desk.",
  "n5:綺麗": "KIREI → KEY RAY: a KEY reflects a RAY of light - PRETTY and CLEAN.",
  "n5:静か": "SHIZUKA → SHE'S A CAR: SHE'S A CAR so QUIET it glides by like a ninja.",
  "n5:賑やか": "NIGIYAKA → KNEE GEE YAK: a festival so LIVELY a YAK dances on its KNEES.",
  "n5:元気": "GENKI → GEN KEY: a power KEY makes you ENERGETIC and HEALTHY - powering up!",
  "n5:有名": "YUUMEI → YOU MAY: 'YOU MAY have my autograph' - says the FAMOUS hero.",
  "n5:親切": "SHINSETSU → SHIN SET SUE: a KIND stranger SETs SUE's bruised SHIN in a bandage.",
  "n5:便利": "BENRI → BEN REE: BEN's gadget belt is so CONVENIENT - grab anything, 'REE!'",
  "n5:暇": "HIMA → HE MA: HE lazes in a hammock with MA - total FREE TIME.",
  "n5:好き": "SUKI → SKI: you LIKE to SKI, so you're FOND of snowy slopes.",
  "n5:嫌い": "KIRAI → KEY RYE: you HATE RYE bread so much you lock it away with a KEY.",
  "n5:大好き": "DAISUKI → DIE SKI: you LOVE skiing so much you'd ski till you DIE.",
  "n5:大嫌い": "DAIKIRAI → DIE KEY RYE: you REALLY HATE RYE - DIE, rye! - you throw away the KEY.",
  "n5:上手": "JOUZU → JOE'S: JOE'S so SKILFUL he juggles katanas blindfolded.",
  "n5:下手": "HETA → HEAT-A: you're BAD AT cooking - the HEAT burns everything to charcoal.",
  "n5:大丈夫": "DAIJOUBU → DIE JOE BOO: Joe falls, DIE? no! 'I'm OK!' - he gives a thumbs up.",
  "n5:大切": "TAISETSU → TIE SET SUE: SUE ties a PRECIOUS charm around her wrist - so IMPORTANT.",
  "n5:大変": "TAIHEN → TIE HEN: TOUGH job - you must TIE up a wild HEN that keeps flapping.",
  "n5:丈夫": "JOUBU → JOE BOO: JOE's shield is so STURDY ghosts go 'BOO' and bounce off.",
  "n5:簡単": "KANTAN → CAN TAN: 'I CAN TAN in a second!' - so EASY and SIMPLE.",
  "n5:嫌": "IYA → EE-YAH!: 'EE-YAH, gross!' - you recoil from something UNPLEASANT.",
  "n5:同じ": "ONAJI → ON A JEEP: twins ride ON A JEEP in the exact SAME outfit.",
  "n5:色々": "IROIRO → EAR-O EAR-O: two EARs pour out VARIOUS colours of paint.",
  "n5:家": "IE → EE-EH: you open the HOUSE door - 'EE-EH, I'm HOME!'",
  "n5:うち": "UCHI → OOCH-EE: you OOCH into your cozy HOME and flop on the couch.",
  "n5:部屋": "HEYA → HEY YA: 'HEY YA!' you shout, bursting into your ROOM.",
  "n5:学校": "GAKKOU → GACK CO: students go 'GACK!' at a SCHOOL test.",
  "n5:大学": "DAIGAKU → DIE GACK: a UNIVERSITY exam so hard students go 'GACK!' and flop.",
  "n5:会社": "KAISHA → KITE SHA: a COMPANY flying a giant KITE logo over its office.",
  "n5:病院": "BYOUIN → BE-YO-IN: 'BE IN bed!' says the doctor at the HOSPITAL.",
  "n5:駅": "EKI → ECK-EE: the train brakes squeal 'ECK-EE!' as it stops at the STATION.",
  "n5:銀行": "GINKOU → GIN COAT: a BANK vault guard wears a shiny silver COAT.",
  "n5:郵便局": "YUUBINKYOKU → YOU BIN KYO-KOO: YOU throw a letter in the BIN at the POST OFFICE.",
  "n5:図書館": "TOSHOKAN → TOE SHOW CAN: you show your TOE in a CAN of books at the LIBRARY - shh!",
  "n5:店": "MISE → ME SAY: 'ME SAY, what does this SHOP sell?' - you browse the shelves.",
  "n5:本屋": "HON'YA → HONE YA: a BOOKSTORE where a skeleton reads a book about HONEs.",
  "n5:八百屋": "YAOYA → YAY-OH-YA: 'YAY!' you shout at the GREENGROCER's giant veggie pile.",
  "n5:花屋": "HANAYA → HAN NIGH-YA: a FLOWER SHOP where HAN is buried in bouquets.",
  "n5:肉屋": "NIKUYA → NICK YA: the BUTCHER NICKs a steak with a giant cleaver.",
  "n5:公園": "KOUEN → CO-EN: CO-op of friends play tag in the PARK.",
  "n5:映画館": "EIGAKAN → EGG CAN: you watch a MOVIE at the THEATER while eating EGGs from a CAN.",
  "n5:交番": "KOUBAN → COBAN: a COP in a tiny POLICE BOX bangs the gong 'BAN!'.",
  "n5:大使館": "TAISHIKAN → 'TIE, SHE CAN': at the embassy gate, a diplomat shows she CAN TIE a perfect necktie to get in.",
  "n5:教室": "KYOUSHITSU → 'CUE SHEETS': the teacher hands out CUE SHEETS to every desk in the classroom.",
  "n5:台所": "DAIDOKORO → 'DIE, DOCK, ROW': in the kitchen, a giant DIE rolls off the counter and DOCKs in a ROW of pots.",
  "n5:お手洗い": "OTEARAI → 'OH, TEAR-RYE': OH no, the restroom sign is TEARing off and has RYE bread stuck to it.",
  "n5:トイレ": "TOIRE → 'TOY-RAY': a TOY RAY gun is floating in the toilet bowl. Don't flush!",
  "n5:風呂": "FURO → 'FOO-ROW': a ROW of rubber ducks shouts FOO! as you sink into the hot bath.",
  "n5:玄関": "GENKAN → 'GHEN CAN': you leave your shoes beside a big tin CAN in the entrance hall.",
  "n5:階段": "KAIDAN → 'KITE DAN': DAN flies a KITE while sprinting up the stairs, three steps at a time.",
  "n5:庭": "NIWA → 'KNEE-WAH': you drop to your KNEEs in the garden and cry WAH at the trampled flowers.",
  "n5:門": "MON → 'MOAN': the old castle gate MOANs loudly as the hero pushes it open.",
  "n5:建物": "TATEMONO → 'TATTY MONO': a TATTY, MONOchrome building, all grey and crumbling, looms over town.",
  "n5:ビル": "BIRU → 'BILL': BILL the giant climbs the office building like a fighter scaling a tower.",
  "n5:アパート": "APAATO → 'A PART-O': you rent A PART of the big apartment block, one tiny window.",
  "n5:ホテル": "HOTERU → 'HOTEL': say HOTEL with a bounce: HO-TE-RU, the hotel bellhop sings it.",
  "n5:デパート": "DEPAATO → 'DEPART-O': shoppers DEPART the department store with arms full of bags.",
  "n5:スーパー": "SUUPAA → 'SUPER': a SUPER-hero cape on the shopping cart at the supermarket.",
  "n5:町": "MACHI → 'MATCHY': every house in town is painted MATCHY-matchy in the same color.",
  "n5:村": "MURA → 'MOO-RAH': cows shout MOO-RAH! in the tiny village square.",
  "n5:国": "KUNI → 'COO-KNEE': a pigeon COOs on the KNEE of a giant map of your country.",
  "n5:外国": "GAIKOKU → 'GUY CO-COO': a GUY travels to a foreign country and every bird there goes CO-COO.",
  "n5:道": "MICHI → 'MEET-CHEESE': two rivals MEET on the road, fighting over a wheel of CHEESE.",
  "n5:橋": "HASHI → 'HUSH-SHE': HUSH! SHE tiptoes across the creaky rope bridge at midnight.",
  "n5:角": "KADO → 'CAR-DOH': your CAR turns the corner too fast. DOH! Scraped the wall.",
  "n5:交差点": "KOUSATEN → 'COAST-A-TEN': cars COAST through the intersection, A TEN-lane crossing.",
  "n5:入口": "IRIGUCHI → 'EERIE GOOEY': the dungeon entrance drips with EERIE GOOEY slime as you walk in.",
  "n5:出口": "DEGUCHI → 'DAY GOOEY': you burst out the exit into bright DAY, still GOOEY from the dungeon.",
  "n5:所": "TOKORO → 'TOCK-ROW': a ROW of clocks going TOCK marks the secret place.",
  "n5:池": "IKE → 'ICKY': the pond is ICKY with green algae and one grumpy frog.",
  "n5:川": "KAWA → 'CAR-WAH': a CAR floats down the river while the driver cries WAH!",
  "n5:海": "UMI → 'OOH, ME!': OOH, ME! the hero yells, leaping into the huge blue sea.",
  "n5:山": "YAMA → 'YAMMER': a climber won't stop YAMMERing all the way up the mountain.",
  "n5:空": "SORA → 'SOAR-A': the hero SOARs high into the open blue sky.",
  "n5:島": "SHIMA → 'SHIMMER': a tiny island SHIMMERs on the horizon like a mirage.",
  "n5:東京": "TOUKYOU → TOKYO: neon towers, packed trains and ramen stalls, the giant capital city.",
  "n5:日本": "NIHON → 'KNEE HONE': you HONE your KNEE-kick on a training trip across Japan.",
  "n5:上": "UE → \"OO-EH?\": OO-EH? you gasp, looking up: the ninja is standing on the roof above you.",
  "n5:下": "SHITA → 'SHEET-A': a cat hides under the bed SHEET, below the mattress.",
  "n5:中": "NAKA → \"KNACK-A\": you have a KNACK for finding the treasure hidden inside the chest.",
  "n5:外": "SOTO → 'SO TOE': SO cold outside your TOE freezes the moment you step out.",
  "n5:右": "MIGI → 'ME GEE': ME, GEE! I punch with my right fist. Always right.",
  "n5:左": "HIDARI → 'HE DARE-y': HE DAREs to dodge left, a sneaky sidestep to the left.",
  "n5:横": "YOKO → 'YO-YO': a YO-YO swings out to your side, beside you.",
  "n5:側": "SOBA → soba noodles: a steaming bowl of SOBA always sits near you, right beside your elbow.",
  "n5:近く": "CHIKAKU → 'CHICK-A-CUP': a CHICK in A CUP sits nearby, close enough to pet.",
  "n5:向こう": "MUKOU → 'MOO-COAL': a cow on a COAL heap MOOs from over there, on the other side.",
  "n5:東": "HIGASHI → 'HE GASHES': the sun rises in the east and HE GASHES the dark sky open with light.",
  "n5:西": "NISHI → 'KNEE-SHE': the sun sets west, glowing on SHE who sits hugging her KNEEs.",
  "n5:南": "MINAMI → 'ME NAMI': ME and NAMI sail south toward warm tropical seas.",
  "n5:北": "KITA → 'KEY-TAR': a rocker plays a KEYTAR on a north-pole iceberg.",
  "n5:後ろ": "USHIRO → 'OO, SHE ROWS': OO! SHE ROWS the boat facing backward, looking behind her.",
  "n5:間": "AIDA → 'EYE DA': an EYE peeks out from between two doors, staring in the gap.",
  "n5:真ん中": "MANNAKA → 'MAN-NACK': a MAN with a KNACK for balance stands right in the middle of the rope.",
  "n5:本": "HON → 'HONE': you HONE your mind with a thick book every night.",
  "n5:雑誌": "ZASSHI → 'ZA SHE': ZAP! SHE flips a glossy magazine full of anime posters.",
  "n5:新聞": "SHINBUN → 'SHIN BUN': the newspaper hits your SHIN and a hot BUN falls out.",
  "n5:辞書": "JISHO → 'GEE, SHOW': GEE, SHOW me that word! You heave open a huge dictionary.",
  "n5:手紙": "TEGAMI → 'TEG, GAMMY': a letter arrives with a GAMMY stamp, hand-delivered by TEG the pigeon.",
  "n5:葉書": "HAGAKI → 'HAG-AH-KEY': a cheerful old HAG mails a postcard with a KEY taped to it.",
  "n5:切手": "KITTE → 'KITTY': a KITTY licks the postage stamp and sticks it on her paw.",
  "n5:封筒": "FUUTOU → 'FOOT-OH': you seal an envelope with your FOOT. OH, it's crumpled now.",
  "n5:紙": "KAMI → 'CALM ME': a sheet of paper floats down and CALMs ME as I fold it into a crane.",
  "n5:鉛筆": "ENPITSU → 'EN-PIT-SUE': SUE drops her pencil in a PIT and has to dig it out.",
  "n5:ペン": "PEN → PEN: same as English, the hero signs a contract with a pen.",
  "n5:ボールペン": "BOORUPEN → 'BALL PEN': a tiny steel BALL rolls the ink in your ballpoint PEN.",
  "n5:万年筆": "MANNENHITSU → 'MAN, 10,000-YEAR HIT': a MAN signs with a fountain pen so old it lasts 10,000 years.",
  "n5:ノート": "NOOTO → 'NOTE': you scribble NOTEs in your notebook during battle training.",
  "n5:鞄": "KABAN → 'CAB BAN': CABs BAN your giant overstuffed bag. It won't fit!",
  "n5:机": "TSUKUE → 'SUE QUEUE': SUE makes the whole class QUEUE up at her desk for homework help.",
  "n5:椅子": "ISU → 'EE, SUE!': EE, SUE! someone pulled away her chair just as she sat down.",
  "n5:窓": "MADO → 'MAD-OH': a MAD crow taps on the window. OH, let it in!",
  "n5:戸": "TO → 'TOE': you stub your TOE on the sliding door. Ouch!",
  "n5:ドア": "DOA → 'DOOR': say DOOR, drop the R: DO-A. The door slams in the villain's face.",
  "n5:テーブル": "TEEBURU → 'TABLE': a TABLE with TEE-shirts piled on it, TEE-BURU.",
  "n5:ベッド": "BEDDO → 'BED-OH': you flop on the BED, OH so soft.",
  "n5:本棚": "HONDANA → 'HON DANNA': DANNA stacks every HON (book) on the bookshelf.",
  "n5:電気": "DENKI → 'DEN KEY': a glowing KEY turns on the light in your DEN with a ZAP of electricity.",
  "n5:テレビ": "TEREBI → 'TELLY-BEE': a BEE crawls across your TELLY during the big anime finale.",
  "n5:ラジオ": "RAJIO → 'RADIO': say RADIO with a J: RA-JI-O crackles from the old radio.",
  "n5:電話": "DENWA → 'DEN-WAH': the phone in your DEN rings and a baby cries WAH into it.",
  "n5:カメラ": "KAMERA → 'CAMERA': same word, CA-ME-RA. Snap the hero's victory pose.",
  "n5:写真": "SHASHIN → 'SHA, SHIN': SHA! the flash goes off and the photo shows only your SHIN.",
  "n5:冷蔵庫": "REIZOUKO → 'RAY ZONE-CO': a freeze RAY ZONE inside the refrigerator chills your snacks.",
  "n5:ストーブ": "SUTOOBU → 'STOVE': a STOVE-like heater glows red in the cold dojo.",
  "n5:箱": "HAKO → 'HACK-O': a ninja HACKs open a mystery box with one sword swipe.",
  "n5:傘": "KASA → 'CASA': rain pours, so you open an umbrella as big as a CASA (house).",
  "n5:鍵": "KAGI → 'CAR GEE': GEE, I locked my CAR! Where's the key?",
  "n5:財布": "SAIFU → 'SIGH, FOO': you SIGH and say FOO when you open your empty wallet.",
  "n5:物": "MONO → 'MONO': a MONOchrome robot sorts every random thing into piles of objects.",
  "n5:眼鏡": "MEGANE → 'MEG, AH NAY': MEG says AH, NAY, I can't see! and pushes up her glasses.",
  "n5:花瓶": "KABIN → 'CABIN': a single flower vase sits on the windowsill of a mountain CABIN.",
  "n5:石鹸": "SEKKEN → 'SECK-KEN': KEN slips on the SOAP and SECKonds later he's on the floor.",
  "n5:タオル": "TAORU → 'TOWEL': say TOWEL slowly, TA-O-RU, while drying off after training.",
  "n5:レコード": "REKOODO → 'RECORD': a vinyl RECORD spins, RE-KOO-DO, scratched by a DJ.",
  "n5:ギター": "GITAA → 'GUITAR': GI-TAA! a rock hero shreds on an electric guitar.",
  "n5:テープ": "TEEPU → 'TAPE': you TAPE a sword back together with duct tape. TEE-PU!",
  "n5:ニュース": "NYUUSU → 'NEWS': breaking NEWS flashes across every screen in the city.",
  "n5:パーティー": "PAATII → 'PARTY': PAA-TII! confetti cannons blast at the victory party.",
  "n5:宿題": "SHUKUDAI → 'SHOOK, OO, DIE': you SHOOK and said OO, I'll DIE when you saw the homework pile.",
  "n5:問題": "MONDAI → 'MONDAY': every MONDAY brings a new problem to solve.",
  "n5:質問": "SHITSUMON → 'SHE'S SUMMONED': SHE raises her hand like she SUMMONED a spirit, to ask a question.",
  "n5:答え": "KOTAE → 'COAT AYE': the answer is written inside your COAT. AYE, that's cheating!",
  "n5:漢字": "KANJI → 'CAN-GEE': you CAN, GEE! Each kanji is a little picture puzzle you crack.",
  "n5:平仮名": "HIRAGANA → 'HERE A GONNA': HERE A curly letter, GONNA write it smooth: hiragana is round and soft.",
  "n5:片仮名": "KATAKANA → 'CUT A CANNA': CUT A CANNA stalk into sharp sticks: katakana is all angular strokes.",
  "n5:英語": "EIGO → 'A GO': A GO at English: you shout HELLO! like a battle cry.",
  "n5:日本語": "NIHONGO → 'KNEE HONE GO': HONE your Japanese, KNEEs bent, GO! like a training montage.",
  "n5:文章": "BUNSHOU → 'BUN SHOW': a SHOW where a BUN writes a long sentence in icing.",
  "n5:作文": "SAKUBUN → 'SACK O' BUNS': you write an essay about a SACK of BUNS for class.",
  "n5:試験": "SHIKEN → 'CHICKEN': a CHICKEN sits the exam beside you and pecks the answers.",
  "n5:テスト": "TESUTO → 'TEST-O': TE-SU-TO, a pop TEST lands on your desk.",
  "n5:授業": "JUGYOU → 'JUG YO': the teacher pours a JUG of facts into class. YO, pay attention!",
  "n5:勉強": "BENKYOU → 'BEN, CUE!': BEN gets his CUE and studies hard in a training montage.",
  "n5:意味": "IMI → 'EE, ME?': EE, ME? What does it mean? You scratch your head over the meaning.",
  "n5:歌": "UTA → 'OOH-TA': the crowd goes OOH-TA! as the singer belts the opening song.",
  "n5:音楽": "ONGAKU → 'ON GAWK-OO': people GAWK as the music turns ON and the bass drops.",
  "n5:映画": "EIGA → 'A GAH': A GAH! moment: the movie villain jumps out on the big screen.",
  "n5:絵": "E → 'EH?': EH? you stare at a strange abstract painting in the gallery.",
  "n5:仕事": "SHIGOTO → 'SHE GOT TO': SHE GOT TO go to work, briefcase in hand, at dawn.",
  "n5:服": "FUKU → 'FOO-COO': a pigeon goes FOO-COO in a tiny set of clothes.",
  "n5:洋服": "YOUFUKU → 'YO, FOO-COO': YO! a pigeon struts in a Western-style suit and tie.",
  "n5:シャツ": "SHATSU → 'SHIRTS': say SHIRTS fast: SHA-TSU. A rack of shirts.",
  "n5:ワイシャツ": "WAISHATSU → 'WHITE SHIRT': a crisp WHITE SHIRT, the dress shirt for a suit.",
  "n5:セーター": "SEETAA → 'SWEATER': SEE-TAA, a cozy knit sweater for cold days.",
  "n5:上着": "UWAGI → 'OO, WAGGY': OO, the dog's WAGGY tail knocks your jacket off the hook.",
  "n5:コート": "KOOTO → 'COAT': KOO-TO, a long hero COAT flaps dramatically in the wind.",
  "n5:ズボン": "ZUBON → 'ZOO BONE': a ZOO lion steals the BONE from your pants pocket.",
  "n5:スカート": "SUKAATO → 'SKIRT': SU-KAA-TO, a skirt twirls in a spinning dance move.",
  "n5:靴": "KUTSU → 'COOT SUE': a COOT bird pecks at SUE's shoes.",
  "n5:靴下": "KUTSUSHITA → 'shoe-under': KUTSU (shoes) + SHITA (under): socks go under your shoes.",
  "n5:帽子": "BOUSHI → 'BOW SHE': SHE takes a BOW and tips her hat to the crowd.",
  "n5:ネクタイ": "NEKUTAI → 'NECKTIE': NE-KU-TAI, a NECKTIE flapping in the wind.",
  "n5:ポケット": "POKETTO → 'POCKET': POKE-TTO, you POKE a hand into your pocket for a coin.",
  "n5:ボタン": "BOTAN → 'BUTTON': BO-TAN, press the big red BUTTON to launch the mech.",
  "n5:体": "KARADA → 'CAR RADAR': a CAR RADAR scans your whole body for battle damage.",
  "n5:頭": "ATAMA → 'AT A MA': AT A MArtial arts class, you get bonked on the head.",
  "n5:目": "ME → 'MEH': your eye rolls: MEH. One big bored eye.",
  "n5:耳": "MIMI → 'ME ME': ME! ME! a bunny with huge ears hears everything.",
  "n5:鼻": "HANA → \"HA, NAH\": HA, NAH, I will not sneeze! says your nose... then ACHOO.",
  "n5:口": "KUCHI → 'COOCHIE-coo': a baby giggles COOCHIE-coo with a big open mouth.",
  "n5:歯": "HA → 'HA!': HA! the villain laughs and shows one shiny gold tooth.",
  "n5:足": "ASHI → 'ASH-EE': you step in hot ASH and hop on one foot: EE!",
  "n5:背": "SE → 'SAY': SAY how tall you are! You stand back to the wall to measure your height.",
  "n5:声": "KOE → 'COY': a COY whisper, then a voice so loud it shatters glass.",
  "n5:病気": "BYOUKI → 'BEE-YOU-KEY': a sick BEE in bed, a thermometer under its tongue.",
  "n5:薬": "KUSURI → 'COO, SURE-E': COO, SURE, I'll take the medicine, says the brave pigeon.",
  "n5:風邪": "KAZE → 'CAR-ZAY': you sneeze so hard with a cold your CAR swerves.",
  "n5:車": "KURUMA → 'CRUISE-MA': MA CRUISEs down the highway in her shiny car.",
  "n5:自動車": "JIDOUSHA → 'GEE, DOE SHA': GEE, a DOE drives an automobile! SHA-zoom.",
  "n5:自転車": "JITENSHA → 'GEE, TEN SHA': GEE, TEN kids pile on one bicycle! SHA-wobble.",
  "n5:電車": "DENSHA → 'DEN SHAKE': the whole DEN SHAKEs when the train roars past.",
  "n5:地下鉄": "CHIKATETSU → 'CHICK-A-TET-SUE': a CHICK and SUE ride the subway deep underground.",
  "n5:バス": "BASU → BUS-OO: a huge city BUS honks 'BUS-OO!' as it drifts around the corner like a race car.",
  "n5:タクシー": "TAKUSHII → TAXI-EE: you whistle 'TAXI-EE!' and a yellow TAXI screeches to a stop at your feet.",
  "n5:飛行機": "HIKOUKI → HEY, COOKIE!: a pilot yells 'HEY, COOKIE!' and tosses snacks out the AIRPLANE window.",
  "n5:船": "FUNE → FOO-NAY: a SHIP's foghorn blasts 'FOO-NAY!' as it sails into the harbor.",
  "n5:切符": "KIPPU → KEEP POO: 'KEEP your POOch off the train!' says the TICKET inspector, punching your TICKET.",
  "n5:旅行": "RYOKOU → RIO COAST: your dream TRIP - surfing the RIO COAST with your whole crew.",
  "n5:天気": "TENKI → TEN KEYS: a weather wizard turns TEN KEYS to switch the WEATHER from storm to sun.",
  "n5:雨": "AME → AH, MAY!: 'AH, MAY showers!' - RAIN pours on your head the moment you step outside.",
  "n5:雪": "YUKI → YUCKY: a SNOWball hits your face - cold, wet, YUCKY SNOW!",
  "n5:風": "KAZE → CAUSE-A: the WIND will CAUSE A hero's cape to flap dramatically on the cliff top.",
  "n5:花": "HANA → HAND-A: a hero pulls a FLOWER from his HAND like a magic trick.",
  "n5:木": "KI → KEY: a giant golden KEY hangs from the branch of an ancient TREE.",
  "n5:動物": "DOUBUTSU → DOUGH BOOTS: ANIMALS at the zoo stomp around wearing squishy DOUGH BOOTS.",
  "n5:犬": "INU → 'IN YOU': a puppy jumps IN YOUr arms and licks your face.",
  "n5:猫": "NEKO → NECK-O: a cat curled around your NECK like a scarf.",
  "n5:鳥": "TORI → TORE-EE: a BIRD swoops down and TORE your sandwich right out of your hand.",
  "n5:馬": "UMA → OOH, MA!: 'OOH, MA, look!' - a white HORSE gallops past at full speed.",
  "n5:牛": "USHI → OO, SHE: 'OO, SHE is big!' - a COW blocks the road and refuses to move.",
  "n5:とても": "TOTEMO → TOTEM-O: a TOTEM pole stacked VERY, VERY high into the clouds.",
  "n5:少し": "SUKOSHI → SKOSH: just a SKOSH - A LITTLE pinch of salt between two fingers.",
  "n5:ちょっと": "CHOTTO → SHOT-TO: 'Just A MOMENT!' - a hero takes A LITTLE SHOT of water mid-fight.",
  "n5:全部": "ZENBU → ZEN BOO: a ZEN monk shouts 'BOO!' and EVERYTHING in the room jumps at once.",
  "n5:皆": "MINNA → MINI-ON: EVERYONE in the stadium turns into tiny MINI-ONs cheering together.",
  "n5:まだ": "MADA → MAD-A: you're still MAD - the hero has NOT YET calmed down. STILL fuming.",
  "n5:また": "MATA → MATADOR: the bull charges the MATADOR AGAIN... and AGAIN... and AGAIN.",
  "n5:すぐ": "SUGU → SUE GOES: SUE GOES IMMEDIATELY - she's out the door before you finish talking.",
  "n5:いつも": "ITSUMO → IT'S MO: IT'S MO's ramen, ALWAYS - he orders the same bowl every single day.",
  "n5:時々": "TOKIDOKI → TOKEN DOCK-EE: SOMETIMES a ship docks and drops a gold TOKEN - but only SOMETIMES.",
  "n5:よく": "YOKU → YOLK-OO: you OFTEN crack eggs WELL - perfect YOLK every time.",
  "n5:あまり": "AMARI → A MARRY: 'A MARRY-age? NOT VERY likely!' - the rival shakes his head.",
  "n5:全然": "ZENZEN → ZEN ZEN: a double-ZEN monk - NOT AT ALL bothered by the explosion behind him.",
  "n5:一番": "ICHIBAN → ITCHY BAN: NUMBER ONE fighter wins the belt, then gets an ITCHY BANdage on top.",
  "n5:もっと": "MOTTO → MOTTO: the team MOTTO is 'MORE! MORE! MORE!' - they never stop training.",
  "n5:ゆっくり": "YUKKURI → YUCKY CURRY: you eat the YUCKY CURRY SLOWLY, one tiny spoonful at a time.",
  "n5:一緒に": "ISSHONI → ISH-SHOW-KNEE: the whole squad does a SHOW, KNEEling TOGETHER in a group pose.",
  "n5:一人で": "HITORIDE → HE TORE A RIDE: HE TORE off on his bike ALONE into the sunset.",
  "n5:本当に": "HONTOUNI → HONEST-OH-KNEE: 'HONESTly, REALLY!' - he swears it down on one KNEE.",
  "n5:初めて": "HAJIMETE → HA, GEE, MET YA!: 'HA, GEE, MET YA!' - meeting your hero FOR THE FIRST TIME.",
  "n5:多分": "TABUN → TA, BUN: 'TA, BUN? PROBABLY...' - you MAYBE want the last bun, but you're not sure.",
  "n5:大体": "DAITAI → DIE TIE: the villain's TIE is ROUGHLY tied - MOSTLY right, a bit crooked.",
  "n5:だんだん": "DANDAN → DUN-DUN: dramatic music goes 'DUN... DUN...' as the boss GRADUALLY gets closer.",
  "n5:ちょうど": "CHOUDO → CHOW DOUGH: the CHOW DOUGH rises to EXACTLY the line - JUST perfect.",
  "n5:まっすぐ": "MASSUGU → MOSS GOO: a slug drags MOSS GOO in a perfectly STRAIGHT line down the path.",
  "n5:どうぞ": "DOUZO → DOZE-OH: 'PLEASE, HERE YOU ARE' - you hand a pillow to a friend ready to DOZE.",
  "n5:どうも": "DOUMO → DOMO: a giant robot bows and booms 'DOMO! THANKS VERY MUCH!'",
  "n5:そう": "SOU → SEW: 'SO you SEW THAT WAY?' - the sensei shows the needle trick.",
  "n5:こう": "KOU → COW: 'Do it LIKE THIS!' - a COW demonstrates the perfect kick.",
  "n5:ああ": "AA → AAAH: 'AH! OH!' - the hero finally gets it, lightbulb over his head.",
  "n5:でも": "DEMO → DEMO: the game DEMO looks great... BUT it ends after one level.",
  "n5:そして": "SOSHITE → SO, SHE TEA: SO SHE made TEA, AND THEN she sat down to fight the boss.",
  "n5:それから": "SOREKARA → SORE CAR: AFTER THAT race, the CAR was SORE all over - and THEN it broke.",
  "n5:じゃあ": "JAA → JAR: 'WELL THEN...' - he closes the cookie JAR and walks off.",
  "n5:すみません": "SUMIMASEN → SUE ME, MASON: 'EXCUSE ME! SUE ME, MASON!' - you bump the builder's ladder.",
  "n5:ごめんなさい": "GOMENNASAI → GO, MEN, NICE EYE: 'I'M SORRY I poked your NICE EYE!' you tell the MEN.",
  "n5:お願いします": "ONEGAISHIMASU → OH, NAG A SHE, MAS: 'PLEASE, PLEASE!' - you NAG your friend for a favor.",
  "n5:ありがとうございます": "ARIGATOU GOZAIMASU → ALLIGATOR, GO SIGH, MAS: you THANK the ALLIGATOR who saved you, and it sighs.",
  "n5:いただきます": "ITADAKIMASU → EAT A DUCK, EE-MAS: 'LET'S EAT!' - the team claps hands before the roast DUCK.",
  "n5:ごちそうさまでした": "GOCHISOUSAMA DESHITA → GOT YOUR SODA, SAM: 'THANKS FOR THE MEAL! GOT YOUR SODA, SAM!' - plates empty.",
  "n5:おはようございます": "OHAYOU GOZAIMASU → OHIO GO SIGH: GOOD MORNING, OHIO! - the sun rises and everyone yawns.",
  "n5:こんにちは": "KONNICHIWA → CONNIE CHEW-WA: HELLO! CONNIE waves while CHEWing gum in the afternoon sun.",
  "n5:こんばんは": "KONBANWA → CON BAN WAR: GOOD EVENING! - the moon rises and they CON-BAN the WAR for the night.",
  "n5:さようなら": "SAYOUNARA → SIGH, YO, NARA: GOODBYE! - the hero SIGHs 'YO...' and walks into the sunset.",
  "n5:おやすみなさい": "OYASUMI NASAI → OH, YA SUMO NASTY: GOOD NIGHT! - a SUMO wrestler snores NASTY loud in bed.",
  "n5:はじめまして": "HAJIMEMASHITE → HA, GEE, ME MASH TEA: HOW DO YOU DO? - first meeting, you nervously MASH the TEA.",
  "n5:どうぞよろしく": "DOUZO YOROSHIKU → DOZE, YO, ROW SHE COO: PLEASED TO MEET YOU! - new teammates bow and shake hands.",
  "n5:行ってらっしゃい": "ITTERASSHAI → EAT-A-RASH, HI!: SEE YOU! - you wave as your friend dashes out the door to battle.",
  "n5:ただいま": "TADAIMA → TA-DA, I'M A...: 'TA-DA! I'M HOME!' - you burst through the door with jazz hands.",
  "n5:お帰りなさい": "OKAERINASAI → OH, CARRY NICE EYE: WELCOME HOME! - family CARRIES your bags, smiling with NICE EYEs.",
  "n5:もしもし": "MOSHIMOSHI → MOSH-MOSH: 'HELLO?' - you answer the PHONE in the middle of a MOSH pit.",
  "n5:結構": "KEKKOU → KEG-COE: 'NO THANK YOU, I'm FINE' - you wave away a whole KEG of soda.",
  "n5:ゼロ": "ZERO → ZERO: a hero's power meter drops to ZERO - a big round empty ring.",
  "n5:半": "HAN → HALF A HAND: you cut a sandwich in HALF with a karate-chop HAN-d.",
  "n5:ページ": "PEEJI → PAGE: a ninja flips the PAGE of a scroll at lightning speed.",
  "n5:メートル": "MEETORU → METER: a hero sprints exactly one METER and collapses dramatically.",
  "n5:キロ": "KIRO → KILO: a strongman lifts a KILO weight with his pinky.",
  "n5:グラム": "GURAMU → GRAM: a tiny GRAM of magic dust explodes like a bomb.",
  "n5:円": "EN → YEN: a shiny round coin worth one YEN rolls into a vending machine - 'EN!'",
  "n5:方": "HOU → HOE: point the HOE in that DIRECTION - THIS SIDE is better for planting.",
  "n5:外国人": "GAIKOKUJIN → GUY COCO GIN: a FOREIGNER steps off the plane holding a COCOnut, waving hello.",
  "n5:留学生": "RYUUGAKUSEI → RYU GOT A SAY: RYU, the INTERNATIONAL STUDENT, finally GOT A SAY in class.",
  "n5:医者": "ISHA → 'IS SHE A...': 'IS SHE A DOCTOR?' - yes, stethoscope swinging, she saves the day.",
  "n5:警官": "KEIKAN → CAKE CAN: a POLICE OFFICER guards a giant CAKE CAN with a whistle.",
  "n5:お巡りさん": "OMAWARISAN → OH, MA, WORRY SAN: 'OH MA, don't WORRY' - the friendly POLICE OFFICER waves hi.",
  "n5:生徒": "SEITO → SAY TOE: the PUPIL has to SAY 'TOE' when the teacher points at her foot.",
  "n5:お客さん": "OKYAKUSAN → OH, KYACK SAN: 'OH, a CUSTOMER!' - the shop bell rings and everyone bows.",
  "n5:子": "KO → KO!: a tiny KID knocks out the big boss - 'K.O.!'",
  "n5:事": "KOTO → COAT-OH: an abstract THING - a mystery COAT floating in the air. What's the MATTER?",
  "n5:時": "TOKI → TOKEN: drop a TOKEN in the clock and TIME starts ticking - WHEN it hits zero, battle!",
  "n5:次": "TSUGI → SUE GEE: 'NEXT!' - SUE yells 'GEE!' as the NEXT challenger enters the ring.",
  "n5:最初": "SAISHO → SIGH SHOW: the FIRST scene of the SHOW - the BEGINNING makes everyone SIGH.",
  "n5:最後": "SAIGO → SIGH, GO: the LAST battle - the hero lets out a final SIGH and says 'GO!'",
  "n5:先": "SAKI → SOCK-EE: race AHEAD - the FIRST runner's SOCK flies off as he dashes in FRONT.",
  "n5:他": "HOKA → HOCKEY: 'Any OTHER sport?' 'HOCKEY! Something ELSE!'",
  "n5:番": "BAN → BAN: it's your TURN - grab NUMBER 7 and BANG the gong. BAN!",
  "n5:お祭り": "OMATSURI → OH, MATS, SURE-EE: a FESTIVAL - lanterns, food stalls, and MATS on the grass.",
  "n5:お土産": "OMIYAGE → OH, ME, YA, GAY!: 'OH, for ME?' - a friend hands you a SOUVENIR keychain from their trip.",
  "n5:プレゼント": "PUREZENTO → PRESENT: a giant PRESENT box explodes with confetti and a robot inside.",
  "n5:スポーツ": "SUPOOTSU → SPORTS: SPORTS day - running, jumping and a ball hit out of the stadium.",
  "n5:プール": "PUURU → POOL: a hero cannonballs into the POOL and empties it with one splash.",
  "n5:クラス": "KURASU → CLASS: the whole CLASS stands and bows as the teacher walks in.",
  "n5:エレベーター": "EREBEETAA → ELEVATOR: the ELEVATOR shoots up like a rocket to the 100th floor.",
  "n5:ゲーム": "GEEMU → GAME: 'GAME over!' flashes on screen as the controller sparks.",
  "n5:ボール": "BOORU → BALL: a fiery soccer BALL spins in the air before the super shot.",
  "n5:シャワー": "SHAWAA → SHOWER: a waterfall-strength SHOWER blasts the hero clean after training.",
  "n5:いかが": "IKAGA → EEK, A GAG: 'HOW about it?' - a waiter offers tea, then EEK, it's A GAG gift.",
  "n5:どちら": "DOCHIRA → DOE CHEER-A: 'WHICH way? WHERE?' - a DOE at a crossroads CHEERs for one path.",
  "n5:こちら": "KOCHIRA → COACH CHEER: 'THIS WAY!' - the COACH CHEERs and points right here.",
  "n5:そちら": "SOCHIRA → SO, CHEER-A: 'THAT WAY - YOUR SIDE!' - fans point across at you and cheer.",
  "n5:あちら": "ACHIRA → AH, CHEER: 'AH, OVER THERE!' - you point to a cheering crowd far away.",
  "n5:どなた": "DONATA → DONATE-A: 'WHO donated this?' - a mystery box with no name on the doorstep.",
  "n5:大勢": "OOZEI → OH, SAY: 'OH, SAY! What a CROWD!' - MANY PEOPLE pack the stadium.",
  "n5:上がる": "AGARU → A GURU: A GURU levitates and RISES UP into the sky.",
  "n5:下がる": "SAGARU → SAGGER-OO: the hero's power bar SAGS and DROPS DOWN to almost empty.",
  "n5:晴れ": "HARE → HARE: a HARE (rabbit) sunbathes under perfect SUNNY skies.",
  "n5:曇り": "KUMORI → COO, MORE: 'COO, MORE clouds?' - CLOUDY gray skies pile up overhead.",
  "n5:火": "HI → HEE!: 'HEE!' - you yelp as a FIRE-breathing dragon singes your eyebrows.",
  "n5:月": "TSUKI → SKI: a ninja SKIs down the crescent MOON at midnight.",
  "n5:日": "HI → HI!: the SUN waves 'HI!' each morning to start a brand-new DAY.",
  "n5:音": "OTO → AUTO: an AUTO alarm SOUND blares - BEEP BEEP BEEP!",
};
